### ISSUE TITLE
Troublshooting deadlocks

### ISSUE THREAD

**Issue by tick-rick** [google/clusterfuzz#1044]
Hello,

I am not here to report a bug, as I am sure it is environmental. I would like some help to find what could be causing this error. It occurs when clicking 'add' on the new job box when uploading a file. I can confirm that gcs writes the file correctly (and returns 200 for the upload POST request, this deadlock appears when requesting the subsequent 127.0.0.1:9000/update-job request). I am running a local instance and I suspect this could be a misconfiguration:

```
Deadlock waiting for <Future 7f7b33125810 created by _put_async(model.py:3474) for tasklet put(context.py:787) suspended generator put(context.py:824); pending> (user@localhost) Traceback (most recent call last):
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/home/user/clusterfuzz/src/appengine/libs/handler.py", line 287, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/clusterfuzz/src/appengine/libs/handler.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/clusterfuzz/src/appengine/handlers/jobs.py", line 140, in post
    job.put()
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/model.py", line 3458, in _put
    return self._put_async(**ctx_options).get_result()
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/tasklets.py", line 380, in check_success
    raise self._exception.__class__, self._exception, self._traceback
RuntimeError: Deadlock waiting for <Future 7f7b33125810 created by _put_async(model.py:3474) for tasklet put(context.py:787) suspended generator put(context.py:824); pending>
```

Edit: Additional notes: Does not occur when not uploading a file for job. It seems to occur inside usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/ext/ndb/context.py, on 'key = yield `self._put_batcher.add(entity, options)` inside `put`

**Comment by tick-rick** [comment]
This does not affect tags/v1.5.1, only master, closing.
