### ISSUE TITLE
jobs-android subscription was missing despite being in queues.yaml

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#1139]
Traceback (most recent call last):
  File "/build/clusterfuzz/bots/HT7BM1A03581/clusterfuzz/src/python/bot/startup/run_bot.py", line 90, in task_loop
    task = tasks.get_task()
  File "/build/clusterfuzz/bots/HT7BM1A03581/clusterfuzz/src/python/base/tasks.py", line 202, in get_task
    task = get_regular_task()
  File "/build/clusterfuzz/bots/HT7BM1A03581/clusterfuzz/src/python/base/tasks.py", line 165, in get_regular_task
    pubsub.subscription_name(application_id, queue), max_messages=1)
  File "/build/clusterfuzz/bots/HT7BM1A03581/clusterfuzz/src/python/google_cloud_utils/pubsub.py", line 161, in pull_from_subscription
    raise RuntimeError('Invalid subscription: ' + subscription)

**Comment by inferno-chromium** [comment]
i created the subscription manually now in google instance, but wonder why only few subscriptions remain there. do they get auto-deleted after unused ?

**Comment by inferno-chromium** [comment]
not urgent, just a question.

**Comment by oliverchang** [comment]
Not sure why they aren't there. I see them in the deployment manager list, but not in the actual subscription list.. I can look more later.
