### ISSUE TITLE
Bots might get stuck on GCS retries

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#1245]
Just accidentally noticed that at least one bot is retrying to read data from GCS for 12 minutes:

```
2019-12-09 22:21:49,444 - run_bot - INFO - Downloading build from url gs://chromium-browser-asan/linux-release-v8-arm/asan-v8-arm-linux-release-723097.zip.
2019-12-09 22:23:32,893 - run_bot - INFO - Checking source code for updates.
2019-12-09 22:23:32,909 - run_bot - INFO - Retrying on google_cloud_utils.storage.read_data failed with unsupported operand type(s) for -: 'tuple' and 'float'. Retrying again.
2019-12-09 22:23:34,913 - run_bot - INFO - Retrying on google_cloud_utils.storage.read_data failed with unsupported operand type(s) for -: 'tuple' and 'float'. Retrying again.
2019-12-09 22:23:38,917 - run_bot - INFO - Retrying on google_cloud_utils.storage.read_data failed with unsupported operand type(s) for -: 'tuple' and 'float'. Retrying again.
2019-12-09 22:23:46,925 - run_bot - INFO - Retrying on google_cloud_utils.storage.read_data failed with unsupported operand type(s) for -: 'tuple' and 'float'. Retrying again.
2019-12-09 22:24:02,942 - run_bot - INFO - Retrying on google_cloud_utils.storage.read_data failed with unsupported operand type(s) for -: 'tuple' and 'float'. Retrying again.
2019-12-09 22:24:34,974 - run_bot - INFO - Retrying on google_cloud_utils.storage.read_data failed with unsupported operand type(s) for -: 'tuple' and 'float'. Retrying again.
2019-12-09 22:25:39,038 - run_bot - INFO - Retrying on google_cloud_utils.storage.read_data failed with unsupported operand type(s) for -: 'tuple' and 'float'. Retrying again.
2019-12-09 22:27:47,137 - run_bot - INFO - Retrying on google_cloud_utils.storage.read_data failed with unsupported operand type(s) for -: 'tuple' and 'float'. Retrying again.
```

what's weird that even killing `run_bot` process doesn't stop this.

**Comment by Dor1s** [comment]
Stacktrace:

```
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/base/retry.py", line 89, in _wrapper
    result = func(*args, **kwargs)
  File "/mnt/scratch0/clusterfuzz/src/python/google_cloud_utils/storage.py", line 834, in read_data
    return _provider().read_data(cloud_storage_file_path)
  File "/mnt/scratch0/clusterfuzz/src/python/google_cloud_utils/storage.py", line 277, in read_data
    return blob.download_as_string()
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/storage/blob.py", line 621, in download_as_string
    self.download_to_file(string_buffer, client=client, start=start, end=end)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/storage/blob.py", line 560, in download_to_file
    self._do_download(transport, file_obj, download_url, headers, start, end)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/storage/blob.py", line 498, in _do_download
    download.consume(transport)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/resumable_media/requests/download.py", line 151, in consume
    result = _helpers.http_request(transport, method, url, **request_kwargs)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/resumable_media/requests/_helpers.py", line 136, in http_request
    return _helpers.wait_and_retry(func, RequestsMixin._get_status_code, retry_strategy)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/resumable_media/_helpers.py", line 150, in wait_and_retry
    response = func()
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/auth/transport/requests.py", line 252, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/auth/transport/requests.py", line 89, in __exit__
    self.remaining_timeout = self._timeout - elapsed
TypeError: unsupported operand type(s) for -: 'tuple' and 'float'
```

**Comment by Dor1s** [comment]
FTW, the bot spent 30 minutes retrying before failing. The error is new and occurring only on the staging bot. Maybe I've deployed an incorrect dependency to it.

**Comment by oliverchang** [comment]
Very likely because of an google-cloud-auth release from an hour ago: https://pypi.org/project/google-auth/#history

**Comment by Dor1s** [comment]
Thanks for digging into this, @oliverchang ! Good luck that we caught it by staging :D

**Comment by oliverchang** [comment]
Should be fixed now.

**Comment by Dor1s** [comment]
I'm seeing another error on a bot now:

```
[mmoroz@35.184.164.25] out: 2019-12-10 05:56:34,297 - run_bot - INFO - Checking for bad build.
[mmoroz@35.184.164.25] out: 2019-12-10 05:56:34,596 - run_bot - INFO - Recorded use of fuzz target libFuzzer_cypher_decrypt_fuzzer.
[mmoroz@35.184.164.25] out: 2019-12-10 05:56:40,345 - run_bot - WARNING - gsutil rsync got non-zero:
[mmoroz@35.184.164.25] out: Command: ['/usr/bin/gsutil', '-m', '-o', 'GSUtil:parallel_thread_count=16', '-q', 'rsync', '-r', '-d', 'gs://clusterfuzz-corpus/libfuzzer/cypher_decrypt_fuzzer/', '/mnt/scratch0/clusterfuzz/bot/inputs/data-bundles/global/cypher_decrypt_fuzzer']
[mmoroz@35.184.164.25] out: Output: Error processing line 1 of /usr/local/lib/python2.7/dist-packages/gae.pth:
[mmoroz@35.184.164.25] out: 
[mmoroz@35.184.164.25] out:   Traceback (most recent call last):
[mmoroz@35.184.164.25] out:     File "/usr/lib/python2.7/site.py", line 158, in addpackage
[mmoroz@35.184.164.25] out:       exec line
[mmoroz@35.184.164.25] out:     File "<string>", line 1, in <module>
[mmoroz@35.184.164.25] out:   ImportError: No module named google
[mmoroz@35.184.164.25] out: 
[mmoroz@35.184.164.25] out: Remainder of file ignored
[mmoroz@35.184.164.25] out: Error processing line 1 of /usr/local/lib/python2.7/dist-packages/gae.pth:
[mmoroz@35.184.164.25] out: 
[mmoroz@35.184.164.25] out:   Traceback (most recent call last):
[mmoroz@35.184.164.25] out:     File "/usr/lib/python2.7/site.py", line 158, in addpackage
[mmoroz@35.184.164.25] out:       exec line
[mmoroz@35.184.164.25] out:     File "<string>", line 1, in <module>
[mmoroz@35.184.164.25] out:   ImportError: No module named google
[mmoroz@35.184.164.25] out: 
[mmoroz@35.184.164.25] out: Remainder of file ignored
[mmoroz@35.184.164.25] out: Traceback (most recent call last):
[mmoroz@35.184.164.25] out:   File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil", line 22, in <module>
[mmoroz@35.184.164.25] out:     gsutil.RunMain()
[mmoroz@35.184.164.25] out:   File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil.py", line 117, in RunMain
[mmoroz@35.184.164.25] out:     sys.exit(gslib.__main__.main())
[mmoroz@35.184.164.25] out:   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 217, in main
[mmoroz@35.184.164.25] out:     gslib.boto_translation.InitializeMultiprocessingVariables()
[mmoroz@35.184.164.25] out:   File "/usr/lib/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 131, in InitializeMultiprocessingVariables
[mmoroz@35.184.164.25] out:     boto_auth_initialized = multiprocessing.Value('i', 0)
[mmoroz@35.184.164.25] out:   File "/usr/lib/python2.7/multiprocessing/__init__.py", line 253, in Value
[mmoroz@35.184.164.25] out:     return Value(typecode_or_type, *args, **kwds)
[mmoroz@35.184.164.25] out:   File "/usr/lib/python2.7/multiprocessing/sharedctypes.py", line 108, in Value
[mmoroz@35.184.164.25] out:     lock = RLock()
[mmoroz@35.184.164.25] out:   File "/usr/lib/python2.7/multiprocessing/__init__.py", line 183, in RLock
[mmoroz@35.184.164.25] out:     return RLock()
[mmoroz@35.184.164.25] out:   File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 172, in __init__
[mmoroz@35.184.164.25] out:     SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1)
[mmoroz@35.184.164.25] out:   File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
[mmoroz@35.184.164.25] out:     sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
[mmoroz@35.184.164.25] out: OSError: [Errno 28] No space left on device
[mmoroz@35.184.164.25] out: 
[mmoroz@35.184.164.25] out: None
[mmoroz@35.184.164.25] out: 2019-12-10 05:56:40,347 - run_bot - INFO - 0 corpus files for target cypher_decrypt_fuzzer synced to disk.
[mmoroz@35.184.164.25] out: 2019-12-10 05:56:40,474 - run_bot - INFO - Cleared system temp directory: /tmp
[mmoroz@35.184.164.25] out: 2019-12-10 05:56:40,636 - run_bot - ERROR - Error occurred while working on task.
[mmoroz@35.184.164.25] out: Traceback (most recent call last):
[mmoroz@35.184.164.25] out:   File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py", line 97, in task_loop
[mmoroz@35.184.164.25] out:     commands.process_command(task)
[mmoroz@35.184.164.25] out:   File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py", line 150, in wrapper
[mmoroz@35.184.164.25] out:     return func(task)
[mmoroz@35.184.164.25] out:   File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py", line 378, in process_command
[mmoroz@35.184.164.25] out:     run_command(task_name, task_argument, job_name)
[mmoroz@35.184.164.25] out:   File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py", line 204, in run_command
[mmoroz@35.184.164.25] out:     task_module.execute_task(task_argument, job_name)
[mmoroz@35.184.164.25] out:   File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1858, in execute_task
[mmoroz@35.184.164.25] out:     session.run()
[mmoroz@35.184.164.25] out:   File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1779, in run
[mmoroz@35.184.164.25] out:     crashes, fuzzer_metadata = self.do_engine_fuzzing(engine_impl)
[mmoroz@35.184.164.25] out:   File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1486, in do_engine_fuzzing
[mmoroz@35.184.164.25] out:     self.sync_corpus(sync_corpus_directory)
[mmoroz@35.184.164.25] out:   File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1291, in sync_corpus
[mmoroz@35.184.164.25] out:     (self.fuzz_target.project_qualified_name(), self.job_type))
[mmoroz@35.184.164.25] out: FuzzTaskException: Failed to sync corpus for fuzzer cypher_decrypt_fuzzer (job libfuzzer_chrome_asan).
```

**Comment by Dor1s** [comment]
Must be an issue with that particular bot. Another one seems to run the staging version well.
