### ISSUE TITLE
error when unziping build

### ISSUE THREAD

**Issue by am06** [google/clusterfuzz#1329]
Hi,

I get the following error when trying to setup locally :

2020-01-12 15:52:52,624 - run_bot - ERROR - Bad zip file /tmp/mybot/clusterfuzz/bot/builds/chrome_asan/custom/asan-linux-release-730105.zip.
Traceback (most recent call last):
  File "/home/adrian/clusterfuzz/src/python/system/archive.py", line 74, in iterator
    with zipfile.ZipFile(archive_obj or archive_path) as zip_file:
  File "/usr/lib/python2.7/zipfile.py", line 793, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 834, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
2020-01-12 15:52:52,626 - run_bot - ERROR - Bad zip file /tmp/mybot/clusterfuzz/bot/builds/chrome_asan/custom/asan-linux-release-730105.zip.
Traceback (most recent call last):
  File "/home/adrian/clusterfuzz/src/python/system/archive.py", line 74, in iterator
    with zipfile.ZipFile(archive_obj or archive_path) as zip_file:
  File "/usr/lib/python2.7/zipfile.py", line 793, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 834, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
2020-01-12 15:52:52,626 - run_bot - ERROR - Unable to unpack build archive /tmp/mybot/clusterfuzz/bot/builds/chrome_asan/custom/asan-linux-release-730105.zip.
Traceback (most recent call last):
  File "/tmp/mybot/clusterfuzz/src/python/build_management/build_manager.py", line 932, in _unpack_custom_build
    archive.unpack(build_local_archive, self.build_dir, trusted=True)
  File "/home/adrian/clusterfuzz/src/python/system/archive.py", line 243, in unpack
    zip_archive = zipfile.ZipFile(zip_file_handle)
  File "/usr/lib/python2.7/zipfile.py", line 793, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 834, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
2020-01-12 15:52:52,627 - run_bot - INFO - Checking for bad build.
2020-01-12 15:52:52,627 - run_bot - ERROR - Exception occurred when running command: .
Traceback (most recent call last):
  File "/home/adrian/clusterfuzz/src/python/system/process_handler.py", line 197, in run_process
    ignore_children=ignore_children)
  File "/tmp/mybot/clusterfuzz/src/third_party/mozprocess/processhandler.py", line 740, in __init__
    (self.cmd, self.args) = (self.cmd[0], self.cmd[1:])
IndexError: list index out of range
2020-01-12 15:52:52,678 - run_bot - INFO - Running fuzzer - python /tmp/mybot/clusterfuzz/bot/inputs/fuzzers/Dharma-Chrome/dharma/dharma/run.py --input_dir=/tmp/mybot/clusterfuzz/bot/inputs/fuzzer-common-data-bundles --output_dir=/tmp/mybot/clusterfuzz/bot/inputs/fuzzer-testcases --no_of_files=1000.
2020-01-12 15:52:54,342 - run_bot - INFO - Locating generated test cases.
2020-01-12 15:52:54,343 - run_bot - INFO - Generated 0/1000 testcases.
2020-01-12 15:52:54,343 - run_bot - ERROR - Fuzzer Dharma-Chrome returned 1. Testcase generation failed.
None
2020-01-12 15:52:54,383 - run_bot - INFO - Uploaded file to logs bucket.
2020-01-12 15:52:54,846 - run_bot - INFO - Using local source, skipping source code update.
2020-01-12 15:52:54,846 - run_bot - INFO - Running platform initialization scripts.
2020-01-12 15:52:55,376 - run_bot - INFO - Completed running platform initialization scripts.
2020-01-12 15:52:55,661 - run_bot - INFO - Executing command 'fuzz Dharma-Chrome chrome_asan'
2020-01-12 15:52:56,163 - run_bot - INFO - Setting up fuzzer and data bundles.
2020-01-12 15:52:56,261 - run_bot - INFO - Retrieving custom binary build r1.

The zip is actually valid, I downloaded from the google chrome bucket.

thanks!

**Comment by inferno-chromium** [comment]
Probably some flake in uploading zip during https://google.github.io/clusterfuzz/setting-up-fuzzing/blackbox-fuzzing/#creating-a-job-type. Can you go to jobs page and try reuploading binary on the job again (don't need to change any job params, just reupload on Custom build button).

**Comment by am06** [comment]
I've decided do use the google chrome bucket to download the build from there (due to limited space in the testing VM)

now I get another error:

20-01-12 16:56:27,824 - run_bot - INFO - Using local source, skipping source code update.
2020-01-12 16:56:27,833 - run_bot - INFO - Running platform initialization scripts.
2020-01-12 16:56:28,359 - run_bot - INFO - Completed running platform initialization scripts.
2020-01-12 16:56:28,855 - run_bot - ERROR - Failed to get any fuzzing tasks. This should not happen.

The new job is created like this:
Env string:
RELEASE_BUILD_BUCKET_PATH=gs://chromium-browser-asan/linux-release/asan-symbolized-linux-release-730106.zip
a1=b1
c1=d1

Templates: engine_asan
Name: ChrromeDharmaAsan
Platform: Linux

Thanks!

**Comment by am06** [comment]
I managed to fixed the above (had to modify & reupload the fuzzer) and now I get this:

2020-01-12 17:08:16,834 - run_bot - INFO - Executing command 'fuzz Dharma-Chrome ChromeDharmaAsan'
2020-01-12 17:08:17,126 - run_bot - INFO - Setting up fuzzer and data bundles.
2020-01-12 17:08:17,165 - run_bot - INFO - Fuzzer update was found, updating.
2020-01-12 17:08:17,247 - run_bot - INFO - Unpacked 68/68.
2020-01-12 17:08:17,248 - run_bot - INFO - Updated fuzzer to revision 6.
2020-01-12 17:08:17,286 - run_bot - ERROR - Error getting list of build urls from gs://chromium-browser-asan/linux-release/asan-symbolized-linux-release-730106.zip.
None
2020-01-12 17:08:17,287 - run_bot - ERROR - Unable to find a matching revision.
None
2020-01-12 17:08:17,287 - run_bot - INFO - Checking for bad build.
2020-01-12 17:08:17,287 - run_bot - ERROR - Exception occurred when running command: .
Traceback (most recent call last):
  File "/home/adrian/clusterfuzz/src/python/system/process_handler.py", line 197, in run_process
    ignore_children=ignore_children)
  File "/tmp/mybot/clusterfuzz/src/third_party/mozprocess/processhandler.py", line 740, in __init__
    (self.cmd, self.args) = (self.cmd[0], self.cmd[1:])
IndexError: list index out of range
2020-01-12 17:08:17,417 - run_bot - INFO - Good build ChromeDharmaAsan.
2020-01-12 17:08:17,459 - run_bot - INFO - Running fuzzer - python /tmp/mybot/clusterfuzz/bot/inputs/fuzzers/Dharma-Chrome/dharma/dharma/run.py --input_dir=/tmp/mybot/clusterfuzz/bot/inputs/fuzzer-common-data-bundles --output_dir=/tmp/mybot/clusterfuzz/bot/inputs/fuzzer-testcases --no_of_files=1000.
2020-01-12 17:08:19,120 - run_bot - INFO - Locating generated test cases.
2020-01-12 17:08:19,120 - run_bot - INFO - Generated 0/1000 testcases.
2020-01-12 17:08:19,121 - run_bot - ERROR - Fuzzer Dharma-Chrome returned 1. Testcase generation failed.

looks like there's aproblem with the GS url I provided......

**Comment by inferno-chromium** [comment]
GSURL needs to be in format
https://google.github.io/clusterfuzz/production-setup/build-pipeline/#providing-the-builds-to-clusterfuzz

so for this chrome one, it should be
RELEASE_BUILD_BUCKET_PATH = gs://chromium-browser-asan/linux-release-chromeos/asan-linux-release-([0-9]+).zip

If you just give a direct url, it is not possible to know which revision it is. So, it needs to be in this format.

**Comment by am06** [comment]
Hi ,

I did the change you requested and now I get this error:

 INFO - Setting up fuzzer and data bundles.
2020-01-13 12:31:01,370 - run_bot - ERROR - Error getting list of build urls from gs://chromium-browser-asan/linux-release-chromeos/asan-linux-release-([0-9]+).zip.
None
2020-01-13 12:31:01,370 - run_bot - ERROR - Unable to find a matching revision.
None
2020-01-13 12:31:01,370 - run_bot - INFO - Checking for bad build.
2020-01-13 12:31:01,371 - run_bot - ERROR - Exception occurred when running command: .
Traceback (most recent call last):
  File "/home/adrian/clusterfuzz/src/python/system/process_handler.py", line 197, in run_process
    ignore_children=ignore_children)
  File "/home/adrian/mybot/clusterfuzz/src/third_party/mozprocess/processhandler.py", line 740, in __init__
    (self.cmd, self.args) = (self.cmd[0], self.cmd[1:])
IndexError: list index out of range

**Comment by inferno-chromium** [comment]
Can you paste your job definition here ?

**Comment by am06** [comment]
Name
ChromeDharmaAsan
 
Platform
LINUX
 
Description (optional)
ChromeDarmaAsanDec
 
Templates (optional)
engine_asan

Custom Build (optional)
File

 
 
Environment String


a1=b1
RELEASE_BUILD_BUCKET_PATH = gs://chromium-browser-asan/linux-release-chromeos/asan-linux-release-([0-9]+).zip

Thanks.

in the meantime I started adding print statements. looks like there's a problem when trying to list the gcp bucket

2020-01-13 15:53:14,740 - run_bot - INFO - Setting up fuzzer and data bundles.
**2020-01-13 15:53:14,863 - run_bot - INFO - Keys file path /home/adrian/mybot/clusterfuzz/bot/build-urls/d14046763285c6784673c425258d6e8d970bda03.list base url gs://chromium-browser-asan/linux-release-chromeos
2020-01-13 15:53:14,864 - run_bot - ERROR - Error getting list of build urls from gs://chromium-browser-asan/linux-release-chromeos/asan-linux-release-([0-9]+).zip.?**
**None
2020-01-13 15:53:14,864 - run_bot - ERROR - Unable to find a matching revision.!!!**

............

**2020-01-13 15:53:20,148 - run_bot - INFO - Keys file path /home/adrian/mybot/clusterfuzz/bot/build-urls/d14046763285c6784673c425258d6e8d970bda03.list base url gs://chromium-browser-asan/linux-release-chromeos**
2020-01-13 15:53:20,148 - run_bot - ERROR - Error getting list of build urls from gs://chromium-browser-asan/linux-release-chromeos/asan-linux-release-([0-9]+).zip.?
None
2020-01-13 15:53:20,148 - run_bot - ERROR - Unable to find a matching revision.!!!

**Comment by inferno-chromium** [comment]
ah, gcs list issue, try another url, this one should be public
RELEASE_BUILD_BUCKET_PATH = gs://chromium-browser-asan/linux-release/asan-linux-release-([0-9]+).zip

**Comment by am06** [comment]
thanks, but I still get the same error:

hromium-browser-asan/linux-release
2020-01-13 16:21:50,090 - run_bot - ERROR - Error getting list of build urls from gs://chromium-browser-asan/linux-release/asan-linux-release-([0-9]+).zip.?
None
2020-01-13 16:21:50,090 - run_bot - ERROR - Unable to find a matching revision.!!!
None
2020-01-13 16:21:50,090 - run_bot - INFO - Checking for bad build.
2020-01-13 16:21:50,092 - run_bot - ERROR - Exception occurred when running command: .
Traceback (most recent call last):
  File "/home/adrian/clusterfuzz/src/python/system/process_handler.py", line 197, in run_process
    ignore_children=ignore_children)
  File "/home/adrian/mybot/clusterfuzz/src/third_party/mozprocess/processhandler.py", line 740, in __init__
    (self.cmd, self.args) = (self.cmd[0], self.cmd[1:])
IndexError: list index out of range

**Comment by inferno-chromium** [comment]
What does 
gsutil ls gs://chromium-browser-asan/linux-release
return ? that bucket is public, so something is up with your google cloud sdk setup.

**Comment by am06** [comment]
it returns output such as:
