### ISSUE TITLE
error fetching build urls

### ISSUE THREAD

**Issue by am06** [google/clusterfuzz#1340]
This is from my bot.log file. A few debug statements have been added by myself.  Thanks.

2020-01-15 22:11:22,538 - run_bot - INFO - Keys file path /home/adrian/mybot/clusterfuzz/bot/build-urls/9ac05ed80077d44bc01a3d0ce4aacbea9bb924dd.list base url gs://chromium-browser-asan/linux-release
2020-01-15 22:11:22,539 - run_bot - ERROR - Error getting list of build urls from gs://chromium-browser-asan/linux-release/asan-linux-release-([0-9]+).zip.?
None
2020-01-15 22:11:22,539 - run_bot - ERROR - Unable to find a matching revision.!!!
None
2020-01-15 22:11:22,540 - run_bot - INFO - Checking for bad build.
2020-01-15 22:11:22,540 - run_bot - ERROR - Exception occurred when running command: .
Traceback (most recent call last):
  File "/home/adrian/clusterfuzz/src/python/system/process_handler.py", line 197, in run_process
    ignore_children=ignore_children)
  File "/home/adrian/mybot/clusterfuzz/src/third_party/mozprocess/processhandler.py", line 740, in __init__
    (self.cmd, self.args) = (self.cmd[0], self.cmd[1:])
IndexError: list index out of range

**Comment by inferno-chromium** [comment]
Does
gsutil ls gs://chromium-browser-asan/linux-release
work for you from command line ?
