### ISSUE TITLE
Frequent port bindings errors

### ISSUE THREAD

**Issue by vadi2** [google/clusterfuzz#136]
While running the heartbleed example this error occurs pretty frequently:

```
| INFO     2019-02-08 13:34:16,999 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| Traceback (most recent call last):
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 96, in <module>
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 96, in <module>
|         _run_file(__file__, globals())
| _run_file(__file__, globals())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 90, in _run_file
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 90, in _run_file
|         execfile(_PATHS.script_file(script_name), globals_)
| execfile(_PATHS.script_file(script_name), globals_)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 199, in <module>
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 199, in <module>
|         main()
| main()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 188, in main
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 188, in main
|         server.start()
| server.start()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 406, in start
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 406, in start
|         raise BindError('Unable to bind %s:%s' % self.bind_addr)
| raise BindError('Unable to bind %s:%s' % self.bind_addr)
| google.appengine.tools.devappserver2.wsgi_servergoogle.appengine.tools.devappserver2.wsgi_server..BindErrorBindError: : Unable to bind localhost:19661Unable to bind localhost:19661
| 
| Traceback (most recent call last):
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 96, in <module>
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 96, in <module>
|         _run_file(__file__, globals())
| _run_file(__file__, globals())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 90, in _run_file
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 90, in _run_file
|         execfile(_PATHS.script_file(script_name), globals_)
| execfile(_PATHS.script_file(script_name), globals_)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 199, in <module>
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 199, in <module>
|         main()
| main()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 188, in main
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 188, in main
|         server.start()
| server.start()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 406, in start
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 406, in start
|         raise BindError('Unable to bind %s:%s' % self.bind_addr)
| raise BindError('Unable to bind %s:%s' % self.bind_addr)
| google.appengine.tools.devappserver2.wsgi_servergoogle.appengine.tools.devappserver2.wsgi_server..BindErrorBindError: : Unable to bind localhost:20010Unable to bind localhost:20010
| 
| ERROR    2019-02-08 13:34:18,749 module.py:974] Request to '/_ah/start' failed
| INFO     2019-02-08 13:34:18,750 module.py:861] cron-service: "GET /_ah/start HTTP/1.1" 500 -
| ERROR    2019-02-08 13:34:18,750 module.py:974] Request to '/_ah/start' failed
| INFO     2019-02-08 13:34:18,750 module.py:861] default: "GET /_ah/start HTTP/1.1" 500 -
| INFO     2019-02-08 13:34:18,961 instance.py:294] Instance PID: 11506
| INFO     2019-02-08 13:34:19,036 instance.py:294] Instance PID: 11519
| INFO     2019-02-08 13:34:19,087 instance.py:294] Instance PID: 11521
| INFO     2019-02-08 13:34:19,120 instance.py:294] Instance PID: 11523
| INFO     2019-02-08 13:34:19,177 instance.py:294] Instance PID: 11524
| INFO     2019-02-08 13:34:19,993 instance.py:294] Instance PID: 11513
| INFO     2019-02-08 13:34:20,082 module.py:861] default: "GET /_ah/stop HTTP/1.1" 500 1954
| INFO     2019-02-08 13:34:20,150 module.py:861] cron-service: "GET /_ah/stop HTTP/1.1" 500 1954
| INFO     2019-02-08 13:34:20,487 module.py:861] cron-service: "GET /_ah/start HTTP/1.1" 404 52
| INFO     2019-02-08 13:34:20,697 module.py:861] cron-service: "GET /_ah/start HTTP/1.1" 404 52
| INFO     2019-02-08 13:34:20,894 module.py:861] default: "GET /_ah/start HTTP/1.1" 404 52
| INFO     2019-02-08 13:34:20,965 module.py:861] default: "GET /_ah/start HTTP/1.1" 404 52
| INFO     2019-02-08 13:34:21,080 module.py:861] default: "GET /_ah/start HTTP/1.1" 404 52
| INFO     2019-02-08 13:34:21,104 module.py:861] cron-service: "GET /_ah/start HTTP/1.1" 404 52
```

**Comment by jonathanmetzman** [comment]
What does `sudo netstat -ltnp | grep -w ':20010'` output when you are running this?
You can kill whatever is listening on port `20010` by running `user -k -n tcp 20010` but I don't actually know if you have something important there on your system so proceed with caution.

**Comment by vadi2** [comment]
It comes up blank when I run it. It tries different port #'s and I don't have many services running - I suspect it's an issue in the application itself trying to double-bind or somesuch?

```
| INFO     2019-02-09 06:30:43,705 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:45,547 instance.py:294] Instance PID: 12997
| Traceback (most recent call last):
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 96, in <module>
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 96, in <module>
|         _run_file(__file__, globals())
| _run_file(__file__, globals())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 90, in _run_file
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 90, in _run_file
|         execfile(_PATHS.script_file(script_name), globals_)
| execfile(_PATHS.script_file(script_name), globals_)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 199, in <module>
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 199, in <module>
|         main()
| main()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 188, in main
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 188, in main
|         server.start()
| server.start()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 406, in start
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 406, in start
|         raise BindError('Unable to bind %s:%s' % self.bind_addr)
| raise BindError('Unable to bind %s:%s' % self.bind_addr)
| google.appengine.tools.devappserver2.wsgi_servergoogle.appengine.tools.devappserver2.wsgi_server..BindErrorBindError: : Unable to bind localhost:15031Unable to bind localhost:15031
| 
| INFO     2019-02-09 06:30:46,268 module.py:861] default: "GET /_ah/stop HTTP/1.1" 200 -
| INFO     2019-02-09 06:30:46,306 module.py:861] cron-service: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:46,319 module.py:861] default: "GET /_ah/start HTTP/1.1" 404 52
| INFO     2019-02-09 06:30:46,346 module.py:861] cron-service: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:46,391 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:46,424 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:46,433 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:46,438 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:46,500 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:46,750 module.py:861] default: "GET /_ah/start HTTP/1.1" 500 1954
| INFO     2019-02-09 06:30:47,549 module.py:861] default: "GET /_ah/stop HTTP/1.1" 500 1954
| INFO     2019-02-09 06:30:49,211 module.py:861] cron-service: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:49,227 module.py:861] cron-service: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:49,231 module.py:861] default: "GET /_ah/start HTTP/1.1" 404 52
| INFO     2019-02-09 06:30:49,236 module.py:861] default: "GET /_ah/stop HTTP/1.1" 200 -
| INFO     2019-02-09 06:30:49,312 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:49,316 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:49,322 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:49,331 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:49,333 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:49,349 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:49,384 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:51,250 instance.py:294] Instance PID: 13187
| INFO     2019-02-09 06:30:51,353 instance.py:294] Instance PID: 13205
| INFO     2019-02-09 06:30:51,413 instance.py:294] Instance PID: 13215
| INFO     2019-02-09 06:30:51,504 instance.py:294] Instance PID: 13219
| INFO     2019-02-09 06:30:51,531 instance.py:294] Instance PID: 13221
| INFO     2019-02-09 06:30:51,931 module.py:861] cron-service: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:51,939 instance.py:294] Instance PID: 13293
| INFO     2019-02-09 06:30:51,978 module.py:861] cron-service: "GET /_ah/stop HTTP/1.1" 200 -
| INFO     2019-02-09 06:30:51,983 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:52,041 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:52,049 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:52,372 module.py:861] default: "GET /_ah/stop HTTP/1.1" 200 -
| INFO     2019-02-09 06:30:52,386 module.py:861] default: "GET /_ah/stop HTTP/1.1" 200 -
| INFO     2019-02-09 06:30:52,605 module.py:861] default: "GET /_ah/stop HTTP/1.1" 200 -
| INFO     2019-02-09 06:30:52,682 module.py:861] default: "GET /_ah/stop HTTP/1.1" 200 -
| INFO     2019-02-09 06:30:54,811 module.py:861] cron-service: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:55,016 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:55,048 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:55,049 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:55,063 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:55,079 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:55,109 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:55,135 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| Traceback (most recent call last):
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 96, in <module>
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 96, in <module>
|         _run_file(__file__, globals())
| _run_file(__file__, globals())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 90, in _run_file
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 90, in _run_file
|         execfile(_PATHS.script_file(script_name), globals_)
| execfile(_PATHS.script_file(script_name), globals_)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 199, in <module>
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 199, in <module>
|         main()
| main()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 188, in main
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 188, in main
|         server.start()
| server.start()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 406, in start
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 406, in start
|         raise BindError('Unable to bind %s:%s' % self.bind_addr)
| raise BindError('Unable to bind %s:%s' % self.bind_addr)
| google.appengine.tools.devappserver2.wsgi_servergoogle.appengine.tools.devappserver2.wsgi_server..BindErrorBindError: : Unable to bind localhost:15190Unable to bind localhost:15190
| 
| INFO     2019-02-09 06:30:55,719 module.py:861] cron-service: "GET /_ah/start HTTP/1.1" 404 52
| INFO     2019-02-09 06:30:56,067 module.py:861] cron-service: "GET /_ah/start HTTP/1.1" 500 1954
| INFO     2019-02-09 06:30:56,461 module.py:861] default: "GET /_ah/start HTTP/1.1" 404 52
| INFO     2019-02-09 06:30:56,720 module.py:861] default: "GET /_ah/start HTTP/1.1" 404 52
| INFO     2019-02-09 06:30:57,009 module.py:861] default: "GET /_ah/start HTTP/1.1" 404 52
| INFO     2019-02-09 06:30:57,057 module.py:861] default: "GET /_ah/start HTTP/1.1" 404 52
| INFO     2019-02-09 06:30:57,610 module.py:861] cron-service: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:57,611 module.py:861] cron-service: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:57,827 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:57,828 instance.py:294] Instance PID: 13509
| INFO     2019-02-09 06:30:57,843 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:57,873 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:57,883 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:57,934 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:57,936 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:30:57,938 module.py:861] cron-service: "GET /_ah/stop HTTP/1.1" 500 1954
| INFO     2019-02-09 06:30:57,941 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| Traceback (most recent call last):
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 96, in <module>
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 96, in <module>
|         _run_file(__file__, globals())
| _run_file(__file__, globals())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 90, in _run_file
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/_python_runtime.py", line 90, in _run_file
|         execfile(_PATHS.script_file(script_name), globals_)
| execfile(_PATHS.script_file(script_name), globals_)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 199, in <module>
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 199, in <module>
|         main()
| main()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 188, in main
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/runtime.py", line 188, in main
|         server.start()
| server.start()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 406, in start
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 406, in start
|         raise BindError('Unable to bind %s:%s' % self.bind_addr)
| raise BindError('Unable to bind %s:%s' % self.bind_addr)
| google.appengine.tools.devappserver2.wsgi_servergoogle.appengine.tools.devappserver2.wsgi_server..BindErrorBindError: : Unable to bind localhost:20367Unable to bind localhost:20367
| 
| INFO     2019-02-09 06:31:00,590 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:31:00,591 module.py:861] cron-service: "GET /_ah/stop HTTP/1.1" 503 -
| INFO     2019-02-09 06:31:00,591 module.py:861] default: "GET /_ah/stop HTTP/1.1" 503 -
```

```
 vadi  ~  Programs  Mudlet  mudlet1  1  sudo netstat -ltnp | grep -w ':15143'
 vadi  ~  Programs  Mudlet  mudlet1  1  sudo netstat -ltnp | grep -w ':22932'
 vadi  ~  Programs  Mudlet  mudlet1  1  sudo netstat -ltnp | grep -w ':20367'
 vadi  ~  Programs  Mudlet  mudlet1  1  
```

**Comment by inferno-chromium** [comment]
see https://github.com/google/clusterfuzz/issues/150#issuecomment-462021601
