### ISSUE TITLE
Fix ML RNN tests for Python 3.

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#1535]
6 out of the remaining 14 failing tests are in ML RNN code:

```
======================================================================
FAIL: test_empty_corpus (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
Test generation should abort for empty corpus.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/ochang/clusterfuzz/src/python/tests/core/bot/fuzzers/ml/rnn/ml_rnn_generator_test.py", line 89, in test_empty_corpus
    self.assertEqual(result.return_code, constants.ExitCode.CORPUS_TOO_SMALL)
AssertionError: 1 != 2

======================================================================
FAIL: test_generate (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
Test generate specified number of inputs.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/ochang/clusterfuzz/src/python/tests/core/bot/fuzzers/ml/rnn/ml_rnn_generator_test.py", line 68, in test_generate
    self.assertEqual(result.return_code, constants.ExitCode.SUCCESS)
AssertionError: 1 != 0

======================================================================
FAIL: test_invalid_model (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
Test TensorFlow should throw exception if model does not match.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/ochang/clusterfuzz/src/python/tests/core/bot/fuzzers/ml/rnn/ml_rnn_generator_test.py", line 114, in test_invalid_model
    self.assertEqual(result.return_code, constants.ExitCode.TENSORFLOW_ERROR)
AssertionError: 1 != 3

======================================================================
FAIL: test_timeout (tests.core.bot.fuzzers.ml.rnn.ml_rnn_generator_test.MLRnnGeneratorIntegrationTest)
Test timeout case in generation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/ochang/clusterfuzz/src/python/tests/core/bot/fuzzers/ml/rnn/ml_rnn_generator_test.py", line 140, in test_timeout
    self.assertTrue(result.timed_out)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 4 tests in 0.427s

FAILED (failures=4)

======================================================================
FAIL: test_small_corpus (tests.core.bot.tasks.ml_train_task_test.MLRnnTrainTaskIntegrationTest)
Test small corpus situation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/ochang/clusterfuzz/src/python/tests/core/bot/tasks/ml_train_task_test.py", line 203, in test_small_corpus
    self.assertEqual(result.return_code, constants.ExitCode.CORPUS_TOO_SMALL)
AssertionError: 1 != 2

======================================================================
FAIL: test_train_rnn (tests.core.bot.tasks.ml_train_task_test.MLRnnTrainTaskIntegrationTest)
Test train RNN model on a simple corpus.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/ochang/clusterfuzz/src/python/tests/core/bot/tasks/ml_train_task_test.py", line 188, in test_train_rnn
    self.assertEqual(result.return_code, constants.ExitCode.SUCCESS)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 6 tests in 0.414s

FAILED (failures=2)
```

**Comment by oliverchang** [comment]
@Dor1s would you have some time this week to help take a look? You can set up a Python 3 env by doing a new checkout and doing:

```
PY3=1 ./local/install_deps.bash
```

(Let me know if that doesn't work).

**Comment by Dor1s** [comment]
Sure, giving a try now
