### ISSUE TITLE
Instability when installing python3 dependencies

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#1648]
Must be some temporary fluke (e.g. networking issue or something else), but reporting this just in case (//cc @oliverchang)

happened two times in a row for me, then succeeded on the third attempt

maybe there is a timeout value we can increase to let it always finish downloading?

```
+ nodeenv -p --prebuilt
 * Install prebuilt node (13.11.0) .Traceback (most recent call last):
  File "/usr/local/google/home/mmoroz/.local/share/virtualenvs/clusterfuzz-UxmpcJs2/bin/nodeenv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/google/home/mmoroz/.local/share/virtualenvs/clusterfuzz-UxmpcJs2/lib/python3.7/site-packages/nodeenv.py", line 927, in main
    create_environment(env_dir, opt)
  File "/usr/local/google/home/mmoroz/.local/share/virtualenvs/clusterfuzz-UxmpcJs2/lib/python3.7/site-packages/nodeenv.py", line 768, in create_environment
    install_node(env_dir, src_dir, opt)
  File "/usr/local/google/home/mmoroz/.local/share/virtualenvs/clusterfuzz-UxmpcJs2/lib/python3.7/site-packages/nodeenv.py", line 640, in install_node
    download_node_src(node_url, src_dir, opt, prefix)
  File "/usr/local/google/home/mmoroz/.local/share/virtualenvs/clusterfuzz-UxmpcJs2/lib/python3.7/site-packages/nodeenv.py", line 527, in download_node_src
    tar_contents = io.BytesIO(urlopen(node_url).read())
  File "/usr/lib/python3.7/http/client.py", line 470, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.7/http/client.py", line 622, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(8847113 bytes read, 24482624 more expected)
```

**Comment by oliverchang** [comment]
Haven't seen this in ages, so closing.
