### ISSUE TITLE
ValueError: virtualenv: cannot access third_party

### ISSUE THREAD

**Issue by kcwu** [google/clusterfuzz#171]
I setup a local instance of clusterfuzz with git HEAD on linux. This is new setup, so no build/fuzzer/any config changes yet.

There is one bot running. Don't know it's relevant or not.

Sometimes I saw the console log of server has error messages like this:
```
| ERROR    2019-02-12 01:31:45,273 wsgi.py:263]
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
|     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 358, in __getattr__
|     self._update_configs()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 294, in _update_configs
|     self._registry.initialize()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 165, in initialize
|     import_func(self._modname)
|   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
|     __import__(name)
|   File "/home/kcwu/src/clusterfuzz/src/appengine/appengine_config.py", line 87, in <module>
|     vendor.add('third_party')
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/ext/vendor/__init__.py", line 44, in add
|     'No such virtualenv or site directory' % path)
| ValueError: virtualenv: cannot access third_party: No such virtualenv or site directory
| INFO     2019-02-12 01:31:45,278 module.py:861] cron-service: "GET /_ah/start HTTP/1.1" 500 -
```

I saw this message more than once, but I don't know how to reproduce it.
BTW, usually "/_ah/start" is 404.
```
| INFO     2019-02-12 01:36:47,518 module.py:861] cron-service: "GET /_ah/start HTTP/1.1" 404 52
```

It's not only failure of "/_ah/start". I have ever seen the error with "/cleanup" and "/triage" as well. Like
```
| ERROR    2019-02-12 01:19:09,738 wsgi.py:263]
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
|     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 358, in __getattr__
|     self._update_configs()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 294, in _update_configs
|     self._registry.initialize()
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/lib_config.py", line 165, in initialize
|     import_func(self._modname)
|   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
|     __import__(name)
|   File "/home/kcwu/src/clusterfuzz/src/appengine/appengine_config.py", line 87, in <module>
|     vendor.add('third_party')
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/ext/vendor/__init__.py", line 44, in add
|     'No such virtualenv or site directory' % path)
| ValueError: virtualenv: cannot access third_party: No such virtualenv or site directory
| INFO     2019-02-12 01:19:09,741 module.py:861] cron-service: "GET /triage HTTP/1.1" 500 -
```

Output of `gcloud version`
```
Google Cloud SDK 233.0.0
alpha 2019.02.04
app-engine-go
app-engine-python 1.9.82
app-engine-python-extras 1.9.82
beta 2019.02.04
bq 2.0.40
cloud-datastore-emulator 2.1.0
core 2019.02.04
gsutil 4.36
kubectl 2019.02.04
pubsub-emulator 2019.02.04
```

BTW, I have ever "gcloud auth"ed for my other project. Don't know it's relevant or not since I run clusterfuzz locally.

**Comment by inferno-chromium** [comment]
The first one run_bot runs, it tries to update third_party which can confuse run_server, but it is just a harmless error. Do you see any error in logs or inability to access `localhost:9000` or any error in bot.log ?

**Comment by kcwu** [comment]
bot.log looks okay. The only error
```
ERROR - Failed to get any fuzzing tasks. This should not happen.
```
because I haven't created fuzzing tasks yet. And it is already documented in the guide.

**Comment by inferno-chromium** [comment]
talked to @kcwu , this was indeed harmless and my last cl should fix this.
