### ISSUE TITLE
Important: Chromium Linux bots are hanging randomly in fuzzing task after py2->3 migration

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#1750]
E.g. clusterfuzz-linux-0d16
clusterfuzz-linux-0188

This one is from clusterfuzz-linux-0d16
```
sudo pystack -v 411278
Standard Output:
[New LWP 411290]
[New LWP 411335]
[New LWP 411362]
[New LWP 411363]
[New LWP 411630]
[New LWP 411631]
[New LWP 411632]
[New LWP 411633]
[New LWP 411634]
[New LWP 411635]
[New LWP 415632]
[New LWP 555768]
[New LWP 1073068]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f554929698d in pthread_join (threadid=140003423549184, thread_return=0x0) at pthread_join.c:90
$1 = (void *) 0x0

Standard Error:
90	pthread_join.c: No such file or directory.

Dumping Threads....


  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 78, in _worker
    work_item = work_queue.get(block=True)

---------------

  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 78, in _worker
    work_item = work_queue.get(block=True)

---------------

  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 470, in _handle_results
    task = get()

---------------

  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 422, in _handle_tasks
    for taskseq, set_length in iter(taskqueue.get, None):

---------------

  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 413, in _handle_workers
    time.sleep(0.1)

---------------

  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()

---------------

  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()

---------------

  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()

---------------

  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/webserver/http_server.py", line 129, in run_server
    httpd.serve_forever()
  File "/usr/local/lib/python3.7/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)

---------------

  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/webserver/http_server.py", line 129, in run_server
    httpd.serve_forever()
  File "/usr/local/lib/python3.7/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)

---------------

  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 78, in _worker
    work_item = work_queue.get(block=True)

---------------

  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/mnt/scratch0/clusterfuzz/src/python/metrics/monitor.py", line 106, in run
    value)
  File "/mnt/scratch0/clusterfuzz/src/python/metrics/monitor.py", line 285, in monitoring_v3_time_series
    self.monitoring_v3_metric(time_series.metric, labels)
  File "/mnt/scratch0/clusterfuzz/src/python/metrics/monitor.py", line 263, in monitoring_v3_metric
    metric.labels['region'] = _get_region(bot_name)
  File "/mnt/scratch0/clusterfuzz/src/python/metrics/monitor.py", line 556, in _get_region
    regions = local_config.MonitoringRegionsConfig()
  File "/mnt/scratch0/clusterfuzz/src/python/config/local_config.py", line 234, in __init__
    super(MonitoringRegionsConfig, self).__init__(MONITORING_REGIONS_PATH)
  File "/mnt/scratch0/clusterfuzz/src/python/config/local_config.py", line 152, in __init__
    if not _validate_root(self._config_dir, self._root):
  File "/mnt/scratch0/clusterfuzz/src/python/config/local_config.py", line 125, in _validate_root
    yaml_path, search_keys, root, value_is_relative_path=False) is not None)
  File "/mnt/scratch0/clusterfuzz/src/python/config/local_config.py", line 55, in _find_key_in_yaml_file
    result = _load_yaml_file(yaml_file_path)
  File "/mnt/scratch0/clusterfuzz/src/python/config/local_config.py", line 46, in _load_yaml_file
    raise errors.ConfigParseError(yaml_file_path)

---------------

  File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py", line 194, in <module>
    main()
  File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py", line 156, in main
    error_stacktrace, clean_exit, task_payload = task_loop()
  File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py", line 99, in task_loop
    commands.process_command(task)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py", line 150, in wrapper
    return func(task)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py", line 378, in process_command
    run_command(task_name, task_argument, job_name)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py", line 204, in run_command
    task_module.execute_task(task_argument, job_name)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1969, in execute_task
    session.run()
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1897, in run
    self.do_blackbox_fuzzing(fuzzer, fuzzer_directory, self.job_type))
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1747, in do_blackbox_fuzzing
    thread.start()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
```

**Comment by inferno-chromium** [comment]
```
(gdb) bt
#0  0x00007f554929698d in pthread_join (threadid=140003423549184, thread_return=0x0) at pthread_join.c:90
#1  0x00007f5541f26d8e in GrpcExecutor::SetThreading(bool) ()
   from /mnt/scratch0/clusterfuzz/src/third_party/grpc/_cython/cygrpc.cpython-37m-x86_64-linux-gnu.so
#2  0x00007f5541f27e6e in grpc_prefork() ()
   from /mnt/scratch0/clusterfuzz/src/third_party/grpc/_cython/cygrpc.cpython-37m-x86_64-linux-gnu.so
#3  0x00007f55488803a5 in __libc_fork () at ../sysdeps/nptl/fork.c:96
#4  0x000000000054c8f5 in os_fork_impl (module=module@entry=0x7f55496192f0) at ./Modules/posixmodule.c:5447
#5  os_fork (module=module@entry=0x7f55496192f0, _unused_ignored=_unused_ignored@entry=0x0) at ./Modules/clinic/posixmodule.c.h:1913
#6  0x000000000043d56c in _PyMethodDef_RawFastCallKeywords (kwnames=0x0, nargs=1231131376, args=0x8bf500 <posix_methods+1120>, 
    self=0x7f55496192f0, method=0x8bf500 <posix_methods+1120>) at Objects/call.c:633
#7  _PyCFunction_FastCallKeywords (func=0x7f554961c6e0, args=args@entry=0x7f553c449bf0, nargs=nargs@entry=0, kwnames=kwnames@entry=0x0)
    at Objects/call.c:734

```

something related to grpc ?

**Comment by oliverchang** [comment]
@mbarbella-chromium we should look at how an alert can catch this.

**Comment by inferno-chromium** [comment]
also unsure if my super speculative fix can even fix this.

**Comment by oliverchang** [comment]
How did you notice this issue btw? And what percentage of bots did this affect?

**Comment by inferno-chromium** [comment]
This was from Michael (V8) email that uploads were not processed faster. What happened here was only few 10 bots non-preemptible bots were alive. Rest were all dead/hung. I recreated bots today, in a few hours, we can see hung bots by looking at /bots page and seeing the recent dead bots. I then went to ssh into one of these and all of these had same hang (used https://pypi.org/project/pystack-debugger/).

**Comment by oliverchang** [comment]
Also yeah, the upgrade may not fix this -- this seems like it could be more an issue with https://github.com/grpc/grpc/issues/18075.

I think one better way we can mitigate this is to disable fork completely by specifying: https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method. This will make things consistent with Windows bots as well.

**Comment by inferno-chromium** [comment]
Bots seems ok now.
