### ISSUE TITLE
ImportError when running reproduce.sh

### ISSUE THREAD

**Issue by quisquous** [google/clusterfuzz#1884]
This is my first time running the clusterfuzz reproduce script since it moved to github.  This is with the `reproduce-tool-stable` tag but is also true at tip of tree.  (Sorry for the noise if this is setup error on my part!)

```
$ ./reproduce.sh -t https://clusterfuzz.com/testcase-detail/anytestcasehere -b /c/src/out/Default/

Traceback (most recent call last):
  File "/c/clusterfuzz/butler.py", line 316, in <module>
    main()
  File "/c/clusterfuzz/butler.py", line 301, in main
    command = importlib.import_module('local.butler.%s' % args.command)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/c/clusterfuzz/src/local/butler/reproduce.py", line 33, in <module>
    from bot import testcase_manager
  File "/c/clusterfuzz/src/python/bot/testcase_manager.py", line 29, in <module>
    from bot.fuzzers import engine_common
  File "/c/clusterfuzz/src/python/bot/fuzzers/engine_common.py", line 36, in <module>
    from bot.fuzzers.ml.rnn import generator as ml_rnn_generator
  File "/c/clusterfuzz/src/python/bot/fuzzers/ml/rnn/generator.py", line 29, in <module>
    from google_cloud_utils import storage
  File "/c/clusterfuzz/src/python/google_cloud_utils/storage.py", line 37, in <module>
    from datastore import locks
  File "/c/clusterfuzz/src/python/datastore/locks.py", line 21, in <module>
    from google.cloud import ndb
  File "/c/clusterfuzz/src/third_party/google/cloud/ndb/__init__.py", line 28, in <module>
    from google.cloud.ndb.client import Client
  File "/c/clusterfuzz/src/third_party/google/cloud/ndb/client.py", line 25, in <module>
    from google.cloud.datastore_v1.gapic import datastore_client
  File "/c/clusterfuzz/src/third_party/google/cloud/datastore_v1/__init__.py", line 18, in <module>
    from google.cloud.datastore_v1.gapic import datastore_client
  File "/c/clusterfuzz/src/third_party/google/cloud/datastore_v1/gapic/datastore_client.py", line 18, in <module>
    import google.api_core.gapic_v1.client_info
  File "/c/clusterfuzz/src/third_party/google/api_core/gapic_v1/__init__.py", line 26, in <module>
    from google.api_core.gapic_v1 import method_async  # noqa: F401
  File "/c/clusterfuzz/src/third_party/google/api_core/gapic_v1/method_async.py", line 20, in <module>
    from google.api_core import general_helpers, grpc_helpers_async
  File "/c/clusterfuzz/src/third_party/google/api_core/grpc_helpers_async.py", line 25, in <module>
    from grpc.experimental import aio
ImportError: cannot import name 'aio' from 'grpc.experimental' (/c/clusterfuzz/src/third_party/grpc/experimental/__init__.py)
```

**Comment by mbarbella-chromium** [comment]
Thanks for the report! Could you give this another try from a fresh checkout?

The reproduce tool stable tag was fairly old, and I was able to reproduce a similar issue. I've updated it to a newer version and it seems to work for me locally. I never saw the exact stack that you were running into, so let me know if it seems to be working now and I'll close this out if so. If you still encounter the same issue I'll take a closer look.

**Comment by quisquous** [comment]
Thanks, seems to work locally for me now!
