### ISSUE TITLE
Hardcode python 3.7 in docker image can cause confusion, mismatch with deployment which can happen on another version like 3.8.

### ISSUE THREAD

**Issue by prestonvanloon** [google/clusterfuzz#1902]
```
Jul 17 00:33:35 clusterfuzz-linux-wc1g bash[6296]: + sudo -E -H -u clusterfuzz bash -c 'PATH='\'':/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\'' PYTHONPATH='\''/mnt/scratch0/clusterfuzz/src'\'' LD_LIBRARY_PATH='\'''\'' python3.7 /mnt/scratch0/clusterfuzz/src/python/bot/startup/run.py'
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]: Traceback (most recent call last):
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:   File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run.py", line 30, in <module>
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:     from base.untrusted import untrusted_noop
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:   File "/mnt/scratch0/clusterfuzz/src/python/base/untrusted.py", line 18, in <module>
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:     from base import tasks
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:   File "/mnt/scratch0/clusterfuzz/src/python/base/tasks.py", line 27, in <module>
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:     from datastore import data_types
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:   File "/mnt/scratch0/clusterfuzz/src/python/datastore/data_types.py", line 22, in <module>
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:     from google.cloud import ndb
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:   File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/__init__.py", line 28, in <module>
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:     from google.cloud.ndb.client import Client
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:   File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/client.py", line 18, in <module>
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:     import grpc
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:   File "/mnt/scratch0/clusterfuzz/src/third_party/grpc/__init__.py", line 23, in <module>
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]:     from grpc._cython import cygrpc as _cygrpc
Jul 17 00:33:38 clusterfuzz-linux-wc1g bash[6296]: ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/mnt/scratch0/clusterfuzz/src/third_party/grpc/_cython/__init__.py)
```

I deployed cluster fuzz from commit 50e3ecca9ba275d8d9ac27ce926ec86c1e61ef64. Not sure how to resolve this. Any ideals?

**Comment by prestonvanloon** [comment]
Not sure if it's relevant, but i saw this during setup

```
| ERROR: google-api-core 1.21.0 has requirement google-auth<2.0dev,>=1.18.0, but you'll have google-auth 1.14.3 which is incompatible.
| ERROR: google-api-core 1.21.0 has requirement protobuf>=3.12.0, but you'll have protobuf 3.11.3 which is incompatible.
```

**Comment by inferno-chromium** [comment]
When you did the deploying of zips, was that run from a python3 version (not python2 and same python3 version as bots).
like python3.7 butler.py deploy
this grpc stuff we see when python versions not matching.

**Comment by prestonvanloon** [comment]
I tried everything again making sure that i was using `python3` and I still have the same issue

**Comment by inferno-chromium** [comment]
What does 
```
ls /mnt/scratch0/clusterfuzz/src/third_party/grpc/_cython
```
show ?
What is your 
```
python3 --version
python3.7 --version
```

**Comment by prestonvanloon** [comment]
ls /var/scratch0/clusterfuzz/src/third_party/grpc/_cython/
```
__init__.py  _credentials  _cygrpc  cygrpc.cpython-38-x86_64-linux-gnu.so
```

I don't have python3.7, but python3 and python3.8 both print Python 3.8.2.

**Comment by prestonvanloon** [comment]
Maybe that is the problem? It looks like the docker image is expecting 3.7, but the setup script allows either 3.7 or 3.8.

https://github.com/google/clusterfuzz/blob/50e3ecca9ba275d8d9ac27ce926ec86c1e61ef64/docker/base/Dockerfile#L88

https://github.com/google/clusterfuzz/blob/master/local/install_deps_linux.bash#L30-L40

**Comment by prestonvanloon** [comment]
OK, that was the problem. I ran the setup with python3.8 when I needed to install and use python3.7.

I'd recommend editing the setup to use the same version as the docker image. Thanks!

**Comment by oliverchang** [comment]
We used to have this bit in our Pipfile:

```
[requires]
python_version = "3.7"
```

I think this would address this. @inferno-chromium I believe we removed this in an attempt to support 3.8 previously, but that never happened, so it should be fine to add this back.

**Comment by inferno-chromium** [comment]
Sure @oliverchang, go ahead and commit this back.
