### ISSUE TITLE
dictionary_manager.py throw exception for old_dictionary_data(decode)

### ISSUE THREAD

**Issue by lion-roadbike** [google/clusterfuzz#1937]
Hello, I see  errors in the bot log: 

```
2020-07-31 08:41:42,049 - run_bot - INFO - Extracting and analyzing recommended dictionary for myapp_xyz_fuzzer.
2020-07-31 08:42:11,864 - run_bot - INFO - 17 out of 20 recommended dictionary elements for myapp_xyz_fuzzer are useless.
2020-07-31 08:42:12,302 - run_bot - ERROR - Error occurred while working on task.
Traceback (most recent call last):
  File "src/python/bot/startup/run_bot.py", line 89, in task_loop
    commands.process_command(task)
  File "/path/to/my-bot/clusterfuzz/src/python/bot/tasks/commands.py", line 147, in wrapper
    return func(task)
  File "/path/to/my-bot/clusterfuzz/src/python/bot/tasks/commands.py", line 377, in process_command
    run_command(task_name, task_argument, job_name)
  File "/path/to/my-bot/clusterfuzz/src/python/bot/tasks/commands.py", line 201, in run_command
    task_module.execute_task(task_argument, job_name)
  File "/path/to/my-bot/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1968, in execute_task
    session.run()
  File "/path/to/my-bot/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1888, in run
    crashes, fuzzer_metadata = self.do_engine_fuzzing(engine_impl)
  File "/path/to/my-bot/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1603, in do_engine_fuzzing
    self.testcase_directory)
  File "/path/to/my-bot/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1301, in run_engine_fuzzer
    fuzz_test_timeout)
  File "/path/to/my-bot/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 334, in fuzz
    arguments)
  File "/path/to/my-bot/clusterfuzz/src/python/bot/fuzzers/libfuzzer.py", line 1485, in analyze_and_update_recommended_dictionary
    recommended_dictionary)
  File "/path/to/my-bot/clusterfuzz/src/python/bot/fuzzers/dictionary_manager.py", line 349, in update_recommended_dictionary
    old_dictionary_data = storage.read_data(self.gcs_path).decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
2020-07-31 08:44:26,344 - run_bot - ERROR - Task exited with exception (payload="fuzz libFuzzer libfuzzer_asan_linux_myapp_xyz_fuzzer").
NoneType: None
2020-07-31 08:44:26,378 - run_bot - INFO - Using local source, skipping source code update.
```

version: tag/v2.0.2
Thank you!

**Comment by inferno-chromium** [comment]
This should not happen as file.read() should return bytes in python3. Are you running unsupported python2 by any change. Also, you are running local run_server and run_bot set up right ?

```
  def read_data(self, remote_path):
    """Read the data of a remote file."""
    fs_path = self.convert_path(remote_path)
    if not os.path.exists(fs_path):
      return None

    with open(fs_path, 'rb') as f:
      return f.read()
```

**Comment by lion-roadbike** [comment]
Yes, running local run_server and run_bot set up are right.
I run with python 3.7.5.

```
(clusterfuzz) root@881ff12e25be:/clusterfuzz# python --version
Python 3.7.5
(clusterfuzz) root@881ff12e25be:/clusterfuzz# /root/.local/share/virtualenvs/clusterfuzz-rAL0Uxhl/bin/python --version
Python 3.7.5
(clusterfuzz) root@881ff12e25be:/clusterfuzz# python3 --version
Python 3.7.5
```

```
(clusterfuzz) root@881ff12e25be:/clusterfuzz# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Jul29 pts/0    00:00:00 /bin/bash
root        16     1  0 Jul29 pts/0    00:00:02 /usr/bin/python3 /usr/local/bin/pipenv shell
root        20    16  0 Jul29 pts/1    00:00:01 /bin/bash -i
root        35    20  0 Jul29 pts/1    00:00:29 python butler.py run_server
root        76    35  0 Jul29 pts/1    00:00:02 python3 /usr/bin/../lib/google-cloud-sdk/lib/gcloud.py beta emulators pubsub 
root       110    76  0 Jul29 pts/1    00:06:36 java -jar /usr/lib/google-cloud-sdk/platform/pubsub-emulator/lib/cloud-pubsub
root       177    35  0 Jul29 pts/1    00:00:11 python3 /usr/bin/../lib/google-cloud-sdk/lib/gcloud.py beta emulators datasto
root       211   177  0 Jul29 pts/1    00:00:00 /bin/bash /usr/lib/google-cloud-sdk/platform/cloud-datastore-emulator/cloud_d
root       213   211  0 Jul29 pts/1    00:11:07 java -cp /usr/lib/google-cloud-sdk/platform/cloud-datastore-emulator/CloudDat
root       270    35  0 Jul29 pts/1    00:00:00 /bin/sh -c go run emulators/gcs.go -storage-path=/clusterfuzz/local/storage/l
root       272   270  0 Jul29 pts/1    00:00:21 go run emulators/gcs.go -storage-path=/clusterfuzz/local/storage/local_gcs
root       276    35  0 Jul29 pts/1    00:00:00 /bin/sh -c gunicorn -b :9009 main:app
root       282   276  0 Jul29 pts/1    00:00:56 /root/.local/share/virtualenvs/clusterfuzz-rAL0Uxhl/bin/python /root/.local/s
root       283    35  0 Jul29 pts/1    00:00:00 /bin/sh -c gunicorn -b :9000 main:app
root       285   283  0 Jul29 pts/1    00:00:59 /root/.local/share/virtualenvs/clusterfuzz-rAL0Uxhl/bin/python /root/.local/s
root       365   285  0 Jul29 pts/1    00:01:04 /root/.local/share/virtualenvs/clusterfuzz-rAL0Uxhl/bin/python /root/.local/s
root       368   282  0 Jul29 pts/1    00:46:56 /root/.local/share/virtualenvs/clusterfuzz-rAL0Uxhl/bin/python /root/.local/s
root       397   272  0 Jul29 pts/1    00:00:19 /tmp/go-build656273195/b001/exe/gcs -storage-path=/clusterfuzz/local/storage/
root     11437    20  0 06:58 pts/1    00:00:00 ps -ef
root     14372    20  0 Jul30 pts/1    00:00:08 python butler.py run_bot --name my-bot /path/to/my-bot
root     14375 14372  0 Jul30 pts/1    00:00:00 /bin/sh -c python src/python/bot/startup/run_bot.py
root     14376 14375  0 Jul30 pts/1    00:13:10 python src/python/bot/startup/run_bot.py
```

**Comment by lion-roadbike** [comment]
I used tag/v2.0.2.
I see this commit, I will try to pull:
#1900 
https://github.com/google/clusterfuzz/commit/601829101e5a277134b5927fcb9556b3b644fd97

Thank you!

**Comment by inferno-chromium** [comment]
We will be doing a new release this week, sorry about the python 2 broken commit.

**Comment by inferno-chromium** [comment]
@oliverchang sheriff for CF release.

**Comment by oliverchang** [comment]
This is now in the latest release (2.1.0).
