### ISSUE TITLE
Panic when launching run_server.py

### ISSUE THREAD

**Issue by DavidKorczynski** [google/clusterfuzz#2077]
I experienced an issue today that I had not seen before, which is a panic that is thrown when creating various pubsub topics and subscriptions. 

```
 Traceback (most recent call last):
  File "butler.py", line 316, in <module>
    main()
  File "butler.py", line 302, in main
    command.execute(args)
  File "src/local/butler/run_server.py", line 155, in execute
    test_utils.setup_pubsub(constants.TEST_APP_ID)
  File "/home/dav/cfuzz/clusterfuzz/src/python/tests/test_libs/test_utils.py", line 291, in setup_pubsub
    create_pubsub_topic(client, project, queue['name'])
  File "/home/dav/cfuzz/clusterfuzz/src/python/tests/test_libs/test_utils.py", line 266, in create_pubsub_topic
    if client.get_topic(full_name):
  File "/home/dav/cfuzz/clusterfuzz/src/python/google_cloud_utils/pubsub.py", line 197, in get_topic
    response = self._execute_with_retry(request)
  File "/home/dav/cfuzz/clusterfuzz/src/python/base/retry.py", line 88, in _wrapper
    result = func(*args, **kwargs)
  File "/home/dav/cfuzz/clusterfuzz/src/python/google_cloud_utils/pubsub.py", line 107, in _execute_with_retry
    return request.execute()
  File "/home/dav/cfuzz/clusterfuzz/src/third_party/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/dav/cfuzz/clusterfuzz/src/third_party/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 500 when requesting http://localhost:9006/v1/projects/test-clusterfuzz/topics/jobs-linux?alt=json returned "Panic! This is a bug!">
```

This is from a fresh installation of clusterfuzz on Ubuntu 18.04. The bug comes after the commands:
```
git clone https://github.com/google/clusterfuzz
cd clusterfuzz
./local/install_deps.bash
python run_server.py --bootstrap```

Do you have any ideas?

**Comment by bin2415** [comment]
Same issue. My environment is Mac Os is 10.15.7.

**Comment by inferno-chromium** [comment]
What is your `gcloud --version` ?

**Comment by inferno-chromium** [comment]
Reproduces for me as well, pretty bad regression.

@oliverchang - can you please take a look.

**Comment by oliverchang** [comment]
This is a pub/sub emulator bug. Looks like it's the same as https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/224. Looking around it seems like the fix should be released soon...

**Comment by oliverchang** [comment]
It seems like it may be another week or so until the fix is released in gcloud. Sadly in the meantime, the only workaround would be to downgrade your gcloud.

**Comment by DavidKorczynski** [comment]
Thanks for clarifying @oliverchang - I will leave this one open in case other people run into the same problem, and then close it when the issue is gone.

**Comment by zounathan** [comment]
With the patch of Dockerfile, I still have the same issue.
(https://github.com/google/clusterfuzz/pull/2096/commits/af1c376fb7e6063ac2772062ebc19faed8f78f85)
Does someone solve this issue?
