### ISSUE TITLE
clusterfuzz not filing bug on Chrome OS

### ISSUE THREAD

**Issue by m-gupta** [google/clusterfuzz#2086]
I see some issues that have been found but no bug was opened e.g. https://clusterfuzz.com/testcase-detail/5722788180852736

When I try to file a bug manually, the UI errors out with following message:

<HttpError 400 when requesting https://monorail-prod.appspot.com/_ah/api/monorail/v1/projects/chromium/issues?sendEmail=true&alt=json returned "Pri field is required.">
Traceback (most recent call last):
  File "/srv/handlers/base_handler.py", line 271, in dispatch_request
    return super(Handler, self).dispatch_request(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/srv/libs/handler.py", line 369, in wrapper
    response = make_response(func(self))
  File "/srv/libs/handler.py", line 438, in wrapper
    return func(self, *args, **kwargs)
  File "/srv/libs/handler.py", line 316, in wrapper
    return func(self, testcase)
  File "/srv/handlers/testcase_detail/create_issue.py", line 60, in post
    self.create_issue(testcase, severity, cc_me)
  File "/srv/handlers/testcase_detail/create_issue.py", line 47, in create_issue
    additional_ccs=additional_ccs)
  File "/srv/libs/issue_management/issue_filer.py", line 411, in file_issue
    issue.save()
  File "/srv/libs/issue_management/monorail/__init__.py", line 162, in save
    self._monorail_issue.save(send_email=notify)
  File "/srv/libs/issue_management/monorail/issue.py", line 279, in save
    self.itm.save(self, send_email)
  File "/srv/libs/issue_management/monorail/issue_tracker_manager.py", line 174, in save
    self._create(issue)
  File "/srv/libs/issue_management/monorail/issue_tracker_manager.py", line 194, in _create
    projectId=self.project_name, sendEmail=send_email, body=body))
  File "python/base/retry.py", line 88, in _wrapper
    result = func(*args, **kwargs)
  File "/srv/libs/issue_management/monorail/issue_tracker_manager.py", line 147, in _execute_with_retry
    return query.execute()
  File "third_party/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "third_party/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://monorail-prod.appspot.com/_ah/api/monorail/v1/projects/chromium/issues?sendEmail=true&alt=json returned "Pri field is required.">

**Comment by m-gupta** [comment]
I currently see 4 issues that are reproducible but do not have any associated bug opened:
https://clusterfuzz.com/?issue=no&open=yes&project=chromeos&reproducible=yes

**Comment by jonathanmetzman** [comment]
Assigning to sheriff.

**Comment by inferno-chromium** [comment]
@mbarbella-chromium - can you add a default priority label for chromium bugs, this is important as it might be breaking all bug filing across monorail. can you check regular chrome bug if they are impacted.

**Comment by mbarbella-chromium** [comment]
Testing the change now, but this should be addressed when #2087 lands.

**Comment by mbarbella-chromium** [comment]
This should now be resolved, though not by the PR mentioned above.
