### ISSUE TITLE
Missing bisect_service pubsub_topic

### ISSUE THREAD

**Issue by urbanenomad** [google/clusterfuzz#2111]
We are seeing a larger number of errors due to the following error.  

2020-10-21 16:04:21,816 - run_bot - ERROR - Error occurred while working on task.
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py", line 89, in task_loop
    commands.process_command(task)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py", line 147, in wrapper
    return func(task)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py", line 377, in process_command
    run_command(task_name, task_argument, job_name)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/commands.py", line 201, in run_command
    task_module.execute_task(task_argument, job_name)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/progression_task.py", line 472, in execute_task
    task_creation.request_bisection(testcase_id)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/task_creation.py", line 257, in request_bisection
    pubsub_topic = local_config.ProjectConfig().get('bisect_service.pubsub_topic')
  File "/mnt/scratch0/clusterfuzz/src/python/config/local_config.py", line 188, in get
    return self._get_helper(key_name, default=default)
  File "/mnt/scratch0/clusterfuzz/src/python/config/local_config.py", line 179, in _get_helper
    value = _search_key(self._config_dir, key_name, value_is_relative_path)
  File "/mnt/scratch0/clusterfuzz/src/python/config/local_config.py", line 136, in _search_key
    value_is_relative_path)
  File "/mnt/scratch0/clusterfuzz/src/python/config/local_config.py", line 64, in _find_key_in_yaml_file
    raise errors.InvalidConfigKey(full_key_name)
base.errors.InvalidConfigKey: Invalid config key project.bisect_service.pubsub_topic.

I can see in the project.yaml file in the config folder there is configuration with the missing pubsub_topic value that is commented out.

bisect_service:
  #pubsub_topic: /projects/project/topics/topic

I looked in our pub/sub list and I don't see any topic specifically listed about bisect service.  Are we missing something?  It looks like the error is occuring because it cannot find this pubsub topic.  Do we need to create this topic?

**Comment by oliverchang** [comment]
Please comment out the "bisect_service:" part completely as well. That should fix it.

**Comment by urbanenomad** [comment]
Ok that looks like that fixed the issue.  I am not seeing that error anymore.  You may want to remove that from the project.yaml file on a default deployment, since it looks like that bisect_service root key makes the bots throw exceptions and crashes.  This may have been the cause of our high read operation of GCS since the bots seemed to crash when it tried to read the key.

**Comment by inferno-chromium** [comment]
> Ok that looks like that fixed the issue. I am not seeing that error anymore. You may want to remove that from the project.yaml file on a default deployment, since it looks like that bisect_service root key makes the bots throw exceptions and crashes. This may have been the cause of our high read operation of GCS since the bots seemed to crash when it tried to read the key.

It is commented out, looks like you accidently uncommented part of it.
See https://github.com/google/clusterfuzz/blob/master/configs/test/project.yaml#L123
