### ISSUE TITLE
deployment problem when set production.

### ISSUE THREAD

**Issue by zhtrb** [google/clusterfuzz#2120]
```
Running: python butler.py run setup --config-dir /home/zht/myconfig --non-dry-run
| Traceback (most recent call last):
|   File "butler.py", line 316, in <module>
|     main()
|   File "butler.py", line 302, in main
|     command.execute(args)
|   File "src/local/butler/run.py", line 41, in execute
|     with ndb_init.context():
|   File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
|     return next(self.gen)
|   File "/home/zht/clusterfuzz/src/python/datastore/ndb_init.py", line 54, in context
|     with _client().context() as ndb_context:
|   File "/home/zht/clusterfuzz/src/python/datastore/ndb_init.py", line 39, in _client
|     _ndb_client = ndb.Client(project=utils.get_application_id())
|   File "/home/zht/clusterfuzz/src/third_party/google/cloud/ndb/client.py", line 118, in __init__
|     project=project, credentials=credentials
|   File "/home/zht/clusterfuzz/src/third_party/google/cloud/client.py", line 227, in __init__
|     Client.__init__(self, credentials=credentials, _http=_http)
|   File "/home/zht/clusterfuzz/src/third_party/google/cloud/client.py", line 132, in __init__
|     credentials, _ = google.auth.default()
|   File "/home/zht/clusterfuzz/src/third_party/google/auth/_default.py", line 321, in default
|     raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
| google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
| Return code is non-zero (1).
| Exit.
Traceback (most recent call last):
  File "butler.py", line 316, in <module>
    main()
  File "butler.py", line 302, in main
    command.execute(args)
  File "src/local/butler/create_config.py", line 283, in execute
    gcloud, args.new_config_dir, appengine_location=args.appengine_location)
  File "src/local/butler/create_config.py", line 200, in deploy_appengine
    '--prod', '--config-dir', config_dir
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'butler.py', 'deploy', '--force', '--targets', 'appengine', '--prod', '--config-dir', '/home/zht/myconfig']' returned non-zero exit status 1.

```
when I run 
```
python butler.py create_config --oauth-client-secrets-path=$CLIENT_SECRETS_PATH \
  --firebase-api-key=$FIREBASE_API_KEY --project-id=$CLOUD_PROJECT_ID $CONFIG_DIR
```
How can I fix this problem.

**Comment by oliverchang** [comment]
Have you you followed https://google.github.io/clusterfuzz/getting-started/prerequisites/#log-in-to-your-google-cloud-account ?

In particular,

```
gcloud auth application-default login
```

**Comment by zhtrb** [comment]
> Have you you followed https://google.github.io/clusterfuzz/getting-started/prerequisites/#log-in-to-your-google-cloud-account ?
> 
> In particular,
> 
> ```
> gcloud auth application-default login
> ```

Thank you. I repeat to follow this page again, especially do this command again and solve the problem.
