### ISSUE TITLE
please help me see this issue , at the bot.log 

### ISSUE THREAD

**Issue by gtt1995** [google/clusterfuzz#2188]
2021-01-07 01:16:52,372 - run_bot - INFO - Strategy pool was generated according to default parameters. Chosen strategies: random_max_len, fork, corpus_mutations_radamsa, entropic, peach_grammar_mutation
2021-01-07 01:16:52,561 - run_bot - ERROR - Error occurred while working on task.
Traceback (most recent call last):
  File "src/python/bot/startup/run_bot.py", line 94, in task_loop
    commands.process_command(task)
  File "/clusterfuzz/bots/localbot2/clusterfuzz/src/python/bot/tasks/commands.py", line 150, in wrapper
    return func(task)
  File "/clusterfuzz/bots/localbot2/clusterfuzz/src/python/bot/tasks/commands.py", line 378, in process_command
    run_command(task_name, task_argument, job_name)
  File "/clusterfuzz/bots/localbot2/clusterfuzz/src/python/bot/tasks/commands.py", line 204, in run_command
    task_module.execute_task(task_argument, job_name)
  File "/clusterfuzz/bots/localbot2/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1969, in execute_task
    session.run()
  File "/clusterfuzz/bots/localbot2/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1889, in run
    crashes, fuzzer_metadata = self.do_engine_fuzzing(engine_impl)
  File "/clusterfuzz/bots/localbot2/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1601, in do_engine_fuzzing
    result, current_fuzzer_metadata, fuzzing_strategies = run_engine_fuzzer(
  File "/clusterfuzz/bots/localbot2/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1297, in run_engine_fuzzer
    options = engine_impl.prepare(sync_corpus_directory, target_path, build_dir)
  File "/clusterfuzz/bots/localbot2/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 109, in prepare
    strategy_info = libfuzzer.pick_strategies(strategy_pool, target_path,
  File "/clusterfuzz/bots/localbot2/clusterfuzz/src/python/bot/fuzzers/libfuzzer.py", line 1748, in pick_strategies
    generator_used = engine_common.generate_new_testcase_mutations(
  File "/clusterfuzz/bots/localbot2/clusterfuzz/src/python/bot/fuzzers/engine_common.py", line 127, in generate_new_testcase_mutations
    generate_new_testcase_mutations_using_radamsa(
  File "/clusterfuzz/bots/localbot2/clusterfuzz/src/python/bot/fuzzers/engine_common.py", line 193, in generate_new_testcase_mutations_using_radamsa
    result = radamsa_runner.run_and_wait(
  File "/clusterfuzz/src/python/system/new_process.py", line 339, in run_and_wait
    process = self.run(
  File "/clusterfuzz/src/python/system/new_process.py", line 289, in run
    subprocess.Popen(
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1603, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError:[Errno 23] too many open files

ERROR task exited with exception (payload="fuzz libfuzzer libfuzzer_asan_libpng").

**Comment by oliverchang** [comment]
This looks like a system configuration issue and not a ClusterFuzz issue. You need to increase the open file limit for your OS.

**Comment by gtt1995** [comment]
thanks,i try it
