### ISSUE TITLE
clusterfuzz(local) run a libfuzzer_job with argument:-jobs=8,workers=8 in the .options file

### ISSUE THREAD

**Issue by gtt1995** [google/clusterfuzz#2190]
As the title says,i just set a bot locally,i want to run parallel libfuzzer in a bot, After the task started for a while, it made an error, the task seemed to be stuck, there were various problems such as the inability to merge the corpus(MERGE-OUTER:failed to parse the control file(unexpected error),the control file in the /clusterfuu/bots/localbot0/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-181449/mcf_tmp_dir/MCF) the number of threads suddenly increased, and the system became sluggish. When I set jobs=8, 260 threads appeared.  when i set jobs= 4, 75 threads appear,
Does the clusterfuzz not support uploading parallel fuzzer（afl-p or libfuzzer(parallel mode)） builds?
look forward your answers.
thanks

**Comment by inferno-chromium** [comment]
It all depends on the bot configuration you have, how many cores it has and how much memory it supports. If you exceed those limits, bot will be in trouble. This is not a clusterfuzz issue. Either use higher end bot, or lower number of jobs/workers.

**Comment by gtt1995** [comment]
thanks very much
and i want to know how can I modify the bot configuration,which one source code should i modify? or,how can i use higher end bot?
thank you for your answer.
thanks

**Comment by inferno-chromium** [comment]
In https://github.com/google/clusterfuzz/blob/master/configs/test/gce/clusters.yaml, change n1-standard-1 to more powerful bots like n1-standard-4 or n1-standard-8, but we still recommend having more lower end bots, than a single powerful bot.

**Comment by gtt1995** [comment]
sorry,i have a try ,but it still not address it
i run clusterfuzz locally  at docker.  the modified configuration does not seem to work.

**Comment by gtt1995** [comment]
Hello,
Still that problem,bot.log as follows,after stuck in this about 1hour,the thread started to expore and the "merged failed" always appeared.
2021-01-10 13:58:54,067 - run_bot - INFO - Using local source, skipping source code update.
2021-01-10 13:58:54,067 - run_bot - INFO - Running platform initialization scripts.
2021-01-10 13:58:54,570 - run_bot - INFO - Completed running platform initialization scripts.
2021-01-10 13:58:54,633 - run_bot - INFO - Executing command 'fuzz libFuzzer libfuzzer_asan_pdf_jobs4'
2021-01-10 13:58:54,861 - run_bot - INFO - Setting up fuzzer and data bundles.
2021-01-10 13:58:54,890 - run_bot - INFO - Retrieving custom binary build r1.
2021-01-10 13:58:54,891 - run_bot - INFO - Build already exists.
2021-01-10 13:58:54,915 - run_bot - INFO - Picked fuzz target fuzz_pdfload for fuzzing.
2021-01-10 13:58:54,915 - run_bot - INFO - Setup application path.
2021-01-10 13:58:54,917 - run_bot - INFO - Checking for bad build.
2021-01-10 13:58:54,920 - run_bot - INFO -     fuzz_target_name = environment.get_value(FUZZ_TARGET)
2021-01-10 13:58:54,920 - run_bot - INFO -     self.fuzz_target = record_fuzz_target(engine_impl.name, fuzz_target_name,
2021-01-10 13:58:54,950 - run_bot - INFO - Recorded use of fuzz target libFuzzer_fuzz_pdfload.
2021-01-10 13:58:54,951 - run_bot - INFO -     environment.set_value(FUZZER_NAME,
2021-01-10 13:58:54,951 - run_bot - INFO - sync_corpus_directory = builtin.get_corpus_directory(
2021-01-10 13:58:54,951 - run_bot - INFO -  self.sync_corpus(sync_corpus_directory)"
2021-01-10 13:58:57,258 - run_bot - INFO - 0 corpus files for target fuzz_pdfload synced to disk.
2021-01-10 13:58:57,259 - run_bot - INFO - environment.reset_current_memory_tool_options(
2021-01-10 13:58:57,261 - run_bot - INFO - for fuzzing_round in range(environment.get_value(MAX_TESTCASS, 1)):
2021-01-10 13:58:57,261 - run_bot - INFO - "logs.log(Fuzzingr1ound {}..format(fuzzing_round))
2021-01-10 13:58:57,261 - run_bot - INFO - Fuzzing round {}..format(fuzzing_round)
2021-01-10 13:58:57,262 - run_bot - INFO - result, current_fuzzer_metadata, fuzzing_strategies = run_engine_fuzzer( engine_impl, self.fuzz_target.binary, sync_corpus_directory, self.testcase_directory)
2021-01-10 13:58:57,262 - run_bot - INFO -   if environment.is_trusted_host():
2021-01-10 13:58:57,262 - run_bot - INFO -   build_dir = environment.get_value(R)
2021-01-10 13:58:57,262 - run_bot - INFO -   target_path = engine_common.find_fuzzer_path(build_dir, target_name)
2021-01-10 13:58:57,263 - run_bot - INFO -   options = engine_impl.prepare(sync_corpus_directory, target_path, build_dir)
2021-01-10 13:58:57,265 - run_bot - INFO - Strategy pool was generated according to default parameters. Chosen strategies: entropic, dataflow_tracing, random_max_len, corpus_subset, peach_grammar_mutation, value_profile, corpus_mutations_ml_rnn
2021-01-10 13:58:57,295 - run_bot - INFO - Corpus is empty. Skip generation.
2021-01-10 13:58:57,296 - run_bot - INFO -   fuzz_test_timeout = environment.get_value()
2021-01-10 13:58:57,296 - run_bot - INFO -   result = engine_impl.fuzz(target_path, options, testcase_directory
"bots/localbot6/clusterfuzz/bot/logs/bot.log" 45150L, 3173145C  

"Merged failed" error information as follows:
2021-01-10 10:33:00,369 - run_bot - INFO - Strategy pool was generated according to default parameters. Chosen strategies: peach_grammar_mutation
2021-01-10 10:33:00,399 - run_bot - INFO -   fuzz_test_timeout = environment.get_value()
2021-01-10 10:33:00,400 - run_bot - INFO -   result = engine_impl.fuzz(target_path, options, testcase_directory
2021-01-10 11:26:03,174 - run_bot - WARNING - Merge failed.
Traceback (most recent call last):
  File "/clusterfuzz/bots/localbot6/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 201, in _merge_new_units
    result = self._minimize_corpus_two_step(
  File "/clusterfuzz/bots/localbot6/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 427, in _minimize_corpus_two_step
    result_2 = self.minimize_corpus(
  File "/clusterfuzz/bots/localbot6/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 490, in minimize_corpus
    raise MergeError('Merging new testcases failed: ' + result.output)
bot.fuzzers.libFuzzer.engine.MergeError: Merging new testcases failed: /clusterfuzz/bots/localbot6/clusterfuzz/bot/builds/libfuzzer_asan_pdf_jobs4/custom/fuzz_pdfload -detect_leaks=0 -timeout=25 -rss_limit_mb=2560 -merge=1 -merge_control_file=/clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-13497/mcf_tmp_dir/MCF /clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-13497/merge-corpus /clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/data-bundles/fuzz_pdfload /clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-13497/new >fuzz-0.log 2>&1
/clusterfuzz/bots/localbot6/clusterfuzz/bot/builds/libfuzzer_asan_pdf_jobs4/custom/fuzz_pdfload -detect_leaks=0 -timeout=25 -rss_limit_mb=2560 -merge=1 -merge_control_file=/clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-13497/mcf_tmp_dir/MCF /clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-13497/merge-corpus /clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/data-bundles/fuzz_pdfload /clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-13497/new >fuzz-1.log 2>&1
================== Job 0 exited with exit code 1 ============
INFO: Seed: 4007126734
INFO: Loaded 1 modules   (19813 inline 8-bit counters): 19813 [0xb9b880, 0xba05e5),
INFO: Loaded 1 PC tables (19813 PCs): 19813 [0x81f3a0,0x86c9f0),
MERGE-OUTER: non-empty control file provided: '/clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-13497/mcf_tmp_dir/MCF'
MERGE-OUTER: control file ok, 3645 files total, first not processed file 0
MERGE-OUTER: attempt 1
INFO: Seed: 4007180401
INFO: Loaded 1 modules   (19813 inline 8-bit counters): 19813 [0xb9b880, 0xba05e5),
INFO: Loaded 1 PC tables (19813 PCs): 19813 [0x81f3a0,0x86c9f0),
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-13497/mcf_tmp_dir/MCF'
MERGE-INNER: 3645 total files; 0 processed earlier; will process 3645 files now
#1      pulse  cov: 336 ft: 337 exec/s: 0 rss: 35Mb
......
......
......
INFO: Seed: 1260698772
INFO: Loaded 1 modules   (19813 inline 8-bit counters): 19813 [0xb9b880, 0xba05e5),
INFO: Loaded 1 PC tables (19813 PCs): 19813 [0x81f3a0,0x86c9f0),
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-13497/mcf_tmp_dir/MCF'
MERGE: failed to parse the control file (unexpected error)
MERGE-OUTER: attempt 4966
INFO: Seed: 1260767214
INFO: Loaded 1 modules   (19813 inline 8-bit counters): 19813 [0xb9b880, 0xba05e5),
INFO: Loaded 1 PC tables (19813 PCs): 19813 [0x81f3a0,0x86c9f0),
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-13497/mcf_tmp_dir/MCF'
MERGE: failed to parse the control file (unexpected error)
MERGE-OUTER: attempt 4967
INFO: Seed: 1260840631
INFO: Loaded 1 modules   (19813 inline 8-bit counters): 19813 [0xb9b880, 0xba05e5),
INFO: Loaded 1 PC tables (19813 PCs): 19813 [0x81f3a0,0x86c9f0),
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/clusterfuzz/bots/localbot6/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-13497/mcf_tmp_dir/MCF'
MERGE: failed to parse the control file (unexpected error)
MERGE-OUTER: the control file has 1040756 bytes
MERGE: failed to parse the control file (unexpected error)

What happened behind this?
How can i solve it?
Also,where is the engine_impl() functions difined？
i am sorry i have a lot questions about this.
look forward your answers.
Wish you happy!
