### ISSUE TITLE
libClusterFuzz accidentally imports modules from dependent projects

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#2192]
To reproduce:
```
pip install clusterfuzz==0.0.1a0
mkdir -p /tmp/myproject
echo "1/0" > /tmp/myproject/metrics.py
cd /tmp/myproject
python -c 'from clusterfuzz import stacktraces'
```

This is the output you get from doing the above:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.venv/lib/python3.8/site-packages/clusterfuzz/stacktraces/__init__.py", line 21, in <module>
    from clusterfuzz._internal.base import utils
  File "/tmp/.venv/lib/python3.8/site-packages/clusterfuzz/_internal/base/utils.py", line 32, in <module>
    from base import memoize
  File "/tmp/.venv/lib/python3.8/site-packages/clusterfuzz/_internal/base/memoize.py", line 23, in <module>
    from base import persistent_cache
  File "/tmp/.venv/lib/python3.8/site-packages/clusterfuzz/_internal/base/persistent_cache.py", line 21, in <module>
    from metrics import logs
  File "/tmp/myproject/metrics.py", line 1, in <module>
    1/0
ZeroDivisionError: division by zero
```

**Comment by jonathanmetzman** [comment]
I think this problem is caused by the fact that both ClusterFuzz and the example project above do not put their code in a proper python package. Instead the example project should be /tmp/myproject/myproject/metrics.py and clusterfuzz should be importing logs like so `from clusterfuzz.metrics import logs`

**Comment by oliverchang** [comment]
Good catch!

Fixing that properly will be pretty involved. Perhaps in the shorter term there's some sys.path hack we can do?

**Comment by jonathanmetzman** [comment]
Hmm...not sure what the sys.path hack would be.
I'll clarify that for now this isn't an immediate problem for me.
I had a script called metrics.py in my top level directory but this script wasn't checked in.
This resulted in a pretty baffling error, but I was able to solve it.
I guess it would be a problem if this issue occured for one of fuzzbench's users.

**Comment by oliverchang** [comment]
I've started on a fix for this.
