### ISSUE TITLE
bot.tasks.fuzz_task.FuzzTaskException: No fuzz targets found

### ISSUE THREAD

**Issue by zjturner** [google/clusterfuzz#2198]
Hi, sorry if this is not the right place to ask general questions.  I didn't find a clusterfuzz-users mailing list and at the bottom of [this page](https://github.com/google/clusterfuzz) it suggests we can ask general questions here.

I'm trying to get local fuzzing working with a test target before I try to set this up in Google Cloud.  I've set everything up what I believe to be correctly.  I've created a fuzzing job in the UI and it shows up in the bot list:

![image](https://user-images.githubusercontent.com/11823433/104528658-b8593a00-55bc-11eb-8fb6-8b1b8e8d49c1.png)

My server is running and showing lots of messages such as:
```
| INFO:root:ClusterFuzz: View (user@localhost): Jobs.
```
as I navigate the web UI.

I'm also running a bot locally:

```
(clusterfuzz) zturner@ubuntu-20:~/src/clusterfuzz$ python3 butler.py run_bot --name testbot ~/testbot/
Created symlink: source: /home/zturner/src/clusterfuzz/configs/test, target /home/zturner/src/clusterfuzz/src/appengine/config.
Creating new CF bot directory...
```

But when I tail -f the bot log, I see this:

```
turner@ubuntu-20:~/testbot/clusterfuzz/bot/logs$ tail -f bot.log
2021-01-13 16:25:42,964 - run_bot - INFO - Using local source, skipping source code update.
2021-01-13 16:25:42,965 - run_bot - INFO - Running platform initialization scripts.
2021-01-13 16:25:43,467 - run_bot - INFO - Completed running platform initialization scripts.
2021-01-13 16:25:43,751 - run_bot - INFO - Executing command 'fuzz libFuzzer lifbuzzer_asan_luautest'
2021-01-13 16:25:43,848 - run_bot - INFO - Setting up fuzzer and data bundles.
2021-01-13 16:25:43,861 - run_bot - INFO - Retrieving custom binary build r1.
2021-01-13 16:26:59,138 - run_bot - INFO - Unpacked 1/1.
2021-01-13 16:26:59,140 - run_bot - INFO - Retrieved custom binary build r1.
2021-01-13 16:26:59,140 - run_bot - INFO - Setup application path.
2021-01-13 16:26:59,140 - run_bot - INFO - Checking for bad build.
2021-01-13 16:26:59,236 - run_bot - ERROR - Error occurred while working on task.
Traceback (most recent call last):
  File "src/python/bot/startup/run_bot.py", line 87, in task_loop
    commands.process_command(task)
  File "/home/zturner/testbot/clusterfuzz/src/python/bot/tasks/commands.py", line 149, in wrapper
    return func(task)
  File "/home/zturner/testbot/clusterfuzz/src/python/bot/tasks/commands.py", line 387, in process_command
    run_command(task_name, task_argument, job_name)
  File "/home/zturner/testbot/clusterfuzz/src/python/bot/tasks/commands.py", line 203, in run_command
    task_module.execute_task(task_argument, job_name)
  File "/home/zturner/testbot/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1997, in execute_task
    session.run()
  File "/home/zturner/testbot/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1917, in run
    crashes, fuzzer_metadata = self.do_engine_fuzzing(engine_impl)
  File "/home/zturner/testbot/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1594, in do_engine_fuzzing
    raise FuzzTaskException('No fuzz targets found.')
bot.tasks.fuzz_task.FuzzTaskException: No fuzz targets found.
```

The contents of the zip that I've uploaded can be seen here, along with a command showing that the fuzzer works when run from the command line:

```
turner@ubuntu-20:~/src/roblox/game-engine/Client/Luau/fuzz$ unzip -l fuzzer-compiler.zip 
Archive:  fuzzer-compiler.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 49621240  2021-01-13 14:49   fuzzer-compiler
---------                     -------
 49621240                     1 file
zturner@ubuntu-20:~/src/roblox/game-engine/Client/Luau/fuzz$ ./fuzzer-compiler -runs=10
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1954631032
INFO: Loaded 1 modules   (59055 inline 8-bit counters): 59055 [0xd90668, 0xd9ed17), 
INFO: Loaded 1 PC tables (59055 PCs): 59055 [0xbc5c30,0xcac720), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED cov: 353 ft: 354 corp: 1/1b exec/s: 0 rss: 36Mb
	NEW_FUNC[1/13]: 0x6b9830 in Luau::BytecodeBuilder::getError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/zturner/src/roblox/game-engine/Client/Luau/fuzz/../src/BytecodeBuilder.cpp:838
	NEW_FUNC[2/13]: 0x7642f0 in Luau::ParseError::~ParseError() /home/zturner/src/roblox/game-engine/Client/Luau/fuzz/../src/Parser.cpp:78
#3	NEW    cov: 393 ft: 404 corp: 2/2b lim: 4 exec/s: 0 rss: 37Mb L: 1/1 MS: 1 ChangeByte-
#4	NEW    cov: 395 ft: 406 corp: 3/4b lim: 4 exec/s: 0 rss: 37Mb L: 2/2 MS: 1 InsertByte-
#5	NEW    cov: 396 ft: 408 corp: 4/6b lim: 4 exec/s: 0 rss: 38Mb L: 2/2 MS: 1 CopyPart-
	NEW_FUNC[1/1]: 0x76fee0 in Luau::Lexer::skipLongSeparator() /home/zturner/src/roblox/game-engine/Client/Luau/fuzz/../src/Parser.cpp:715
#7	NEW    cov: 402 ft: 414 corp: 5/7b lim: 4 exec/s: 0 rss: 38Mb L: 1/2 MS: 2 ShuffleBytes-ChangeByte-
#8	NEW    cov: 404 ft: 416 corp: 6/9b lim: 4 exec/s: 0 rss: 38Mb L: 2/2 MS: 1 InsertByte-
#9	NEW    cov: 404 ft: 418 corp: 7/12b lim: 4 exec/s: 0 rss: 38Mb L: 3/3 MS: 1 CopyPart-
#10	DONE   cov: 404 ft: 418 corp: 7/12b lim: 4 exec/s: 0 rss: 38Mb
Done 10 runs in 0 second(s)
```

Have I messed something up?

**Comment by oliverchang** [comment]
Are you able to share the zip file here somewhere?

Is the binary in the zip an ELF binary with the string "LLVMFuzzerTestOneInput" in there somewhere? (e.g. from the output of `strings fuzzer-compiler`.

Alternatively, you can try to rename the file in the zip to something ending in "_fuzzer". e.g. "compiler_fuzzer".

**Comment by zjturner** [comment]
Oh man, I think my mild dyslexia got the best of me.  I spelled "libfuzzer" wrong in the name of the job (look closely).  I'm trying again with a correct spelling

**Comment by zjturner** [comment]
It gets further now:

```
021-01-13 16:43:13,658 - run_bot - INFO - Setup application path.
2021-01-13 16:43:13,667 - run_bot - INFO - Checking for bad build.
2021-01-13 16:43:13,691 - run_bot - INFO - Recorded use of fuzz target libFuzzer_fuzzer-compiler.
2021-01-13 16:43:15,088 - run_bot - INFO - 0 corpus files for target fuzzer-compiler synced to disk.
2021-01-13 16:43:15,088 - run_bot - INFO - Fuzzing round 0.
2021-01-13 16:43:15,089 - run_bot - INFO - Strategy pool was generated according to default parameters. Chosen strategies: fork, corpus_mutations_radamsa, peach_grammar_mutation
```

Two questions:
1. How do I specify command line options that will be passed to the fuzz target?  For example, locally I would run this with the `-dict` option.  
2. Am I supposed to see output?  It's sitting there after "Strategy pool was generated" and I don't see any more output in either the bot's log or the bot's stdout.

**Comment by oliverchang** [comment]
1. See https://google.github.io/oss-fuzz/getting-started/new-project-guide/#dictionaries. Easiest way is just to have a fuzzer-compiler.dict file.

2. This is normal. You won't see real time output in these logs.

**Comment by zjturner** [comment]
I guess it's working but just not finding any bugs since we've fuzzed this offline in the past.  I'll try a dummy target with obvious flaws and post back if I'm still running into trouble.

Thanks so much for your help.
