### ISSUE TITLE
dav1d fails to clone in run.py script

### ISSUE THREAD

**Issue by pmatos** [google/clusterfuzz#2225]
The `run.py` script, which I was looking at contains a line that is currently failing:

https://github.com/google/clusterfuzz/blob/17dc87e1a41b5d2cffe7702d5528a18a50b42c33/src/python/scripts/other-bots/chromium-tests-syncer/run.py#L233

When running this line, I get issues cloning `dav1d`:
```
fetch --no-history chromium --nosvn=True
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "name": "src",
    "url": "https://chromium.googlesource.com/chromium/src.git",
    "managed": False,
    "custom_deps": {},
    "custom_vars": {},
  },
]
'
Running: gclient sync --no-history

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/chromium/src.git --depth=1 /home/pmatos/tmp/foobar/_gclient_src_ckojwap6' in '/home/pmatos/tmp/foobar'
Cloning into '/home/pmatos/tmp/foobar/_gclient_src_ckojwap6'...
remote: Counting objects: 352243, done
remote: Finding sources: 100% (352243/352243)
remote: Total 352243 (delta 76622), reused 234217 (delta 76622)
Receiving objects: 100% (352243/352243), 1.09 GiB | 10.06 MiB/s, done.
Resolving deltas: 100% (76622/76622), done.
24>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/external/github.com/videolan/dav1d.git" "--template=/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_gittmp_libdav1d94ngj1hj" "/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74"' in /home/pmatos/tmp/foobar failed; will retry after a short nap...
24>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/external/github.com/videolan/dav1d.git" "--template=/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_gittmp_libdav1d94ngj1hj" "/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74"' in /home/pmatos/tmp/foobar failed; will retry after a short nap...
24>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/external/github.com/videolan/dav1d.git" "--template=/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_gittmp_libdav1d94ngj1hj" "/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74"' in /home/pmatos/tmp/foobar failed; will retry after a short nap...
24>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/external/github.com/videolan/dav1d.git" "--template=/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_gittmp_libdav1d94ngj1hj" "/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74"' in /home/pmatos/tmp/foobar failed; will retry after a short nap...
Syncing projects:  97% (33/34) src/native_client                       
src/third_party/dav1d/libdav1d (ERROR)
----------------------------------------
[0:03:22] Started.
[0:03:22] 

________ running 'git init --bare /home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_gittmp_libdav1d94ngj1hj' in '/home/pmatos/tmp/foobar'

[0:03:22] Initialized empty Git repository in /home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_gittmp_libdav1d94ngj1hj/
[0:03:22] 
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/videolan/dav1d.git --template=/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_gittmp_libdav1d94ngj1hj /home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74' in '/home/pmatos/tmp/foobar'

[0:03:22] Cloning into '/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74'...
[0:03:23] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:03:23] fatal: error reading section header 'shallow-info'
[0:03:23] 
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/videolan/dav1d.git --template=/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_gittmp_libdav1d94ngj1hj /home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74' in '/home/pmatos/tmp/foobar' attempt 2 / 4

[0:03:23] Cloning into '/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74'...
[0:03:23] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:03:23] fatal: error reading section header 'shallow-info'
[0:03:24] 
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/videolan/dav1d.git --template=/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_gittmp_libdav1d94ngj1hj /home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74' in '/home/pmatos/tmp/foobar' attempt 3 / 4

[0:03:24] Cloning into '/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74'...
[0:03:25] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:03:25] fatal: error reading section header 'shallow-info'
[0:03:27] 
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/videolan/dav1d.git --template=/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_gittmp_libdav1d94ngj1hj /home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74' in '/home/pmatos/tmp/foobar' attempt 4 / 4

[0:03:27] Cloning into '/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74'...
[0:03:28] error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
[0:03:28] fatal: error reading section header 'shallow-info'
Traceback (most recent call last):
  File "/home/pmatos/dev/depot_tools/gclient_scm.py", line 1043, in _Clone
    self._Run(clone_cmd, options, cwd=self._root_dir, retry=True,
  File "/home/pmatos/dev/depot_tools/gclient_scm.py", line 1411, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "/home/pmatos/dev/depot_tools/gclient_utils.py", line 673, in CheckCallAndFilter
    raise subprocess2.CalledProcessError(
subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/videolan/dav1d.git --template=/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_gittmp_libdav1d94ngj1hj /home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74' returned non-zero exit status 128 in /home/pmatos/tmp/foobar
[0:03:32] _____ Conflicting directory found in /home/pmatos/tmp/foobar/src/third_party/dav1d/libdav1d. Moving to /home/pmatos/tmp/foobar/_bad_scm/src/third_party/dav1d/libdav1d6ocdk9ds.
----------------------------------------


Warnings:
Conflicting directory /home/pmatos/tmp/foobar/src/third_party/dav1d/libdav1d moved to /home/pmatos/tmp/foobar/_bad_scm/src/third_party/dav1d/libdav1d6ocdk9ds.
Traceback (most recent call last):
  File "/home/pmatos/dev/depot_tools/gclient_scm.py", line 546, in update
    self._Clone(revision, url, options)
  File "/home/pmatos/dev/depot_tools/gclient_scm.py", line 1043, in _Clone
    self._Run(clone_cmd, options, cwd=self._root_dir, retry=True,
  File "/home/pmatos/dev/depot_tools/gclient_scm.py", line 1411, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "/home/pmatos/dev/depot_tools/gclient_utils.py", line 673, in CheckCallAndFilter
    raise subprocess2.CalledProcessError(
subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/external/github.com/videolan/dav1d.git --template=/home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_gittmp_libdav1d94ngj1hj /home/pmatos/tmp/foobar/src/third_party/dav1d/_gclient_libdav1d_3gy7uj74' returned non-zero exit status 128 in /home/pmatos/tmp/foobar

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pmatos/.vpython-root/bbfa3b/lib/python3.8/shutil.py", line 780, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pmatos/tmp/foobar/src/third_party/dav1d/libdav1d' -> '/home/pmatos/tmp/foobar/_bad_scm/src/third_party/dav1d/libdav1d6ocdk9ds/libdav1d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pmatos/dev/depot_tools/metrics.py", line 267, in print_notice_and_exit
    yield
  File "/home/pmatos/dev/depot_tools/gclient.py", line 3199, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/pmatos/dev/depot_tools/gclient.py", line 3185, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/home/pmatos/dev/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/home/pmatos/dev/depot_tools/gclient.py", line 2739, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/home/pmatos/dev/depot_tools/gclient.py", line 1779, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options,
  File "/home/pmatos/dev/depot_tools/gclient_utils.py", line 968, in flush
    reraise(e[0], e[1], e[2])
  File "/home/pmatos/dev/depot_tools/gclient_utils.py", line 67, in reraise
    raise value
  File "/home/pmatos/dev/depot_tools/gclient_utils.py", line 1045, in run
    self.item.run(*self.args, **self.kwargs)
  File "/home/pmatos/dev/depot_tools/gclient.py", line 925, in run
    self._got_revision = self._used_scm.RunCommand(command, options, args,
  File "/home/pmatos/dev/depot_tools/gclient_scm.py", line 132, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/home/pmatos/dev/depot_tools/gclient_scm.py", line 548, in update
    self._DeleteOrMove(options.force)
  File "/home/pmatos/dev/depot_tools/gclient_scm.py", line 207, in _DeleteOrMove
    shutil.move(self.checkout_path, dest_path)
  File "/home/pmatos/.vpython-root/bbfa3b/lib/python3.8/shutil.py", line 794, in move
    copy_function(src, real_dst)
  File "/home/pmatos/.vpython-root/bbfa3b/lib/python3.8/shutil.py", line 426, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/pmatos/.vpython-root/bbfa3b/lib/python3.8/shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pmatos/tmp/foobar/src/third_party/dav1d/libdav1d'
```

**Comment by inferno-chromium** [comment]
Not a clusterfuzz issue, looks like a bad checkout/bad network connection. delete dir and retry.
