### ISSUE TITLE
Unable to run a local server

### ISSUE THREAD

**Issue by loveiset** [google/clusterfuzz#223]
## problem
After install successfully, I run a local server by
```
python butler.py run_server
# or
python butler.py run_server --bootstrap
```
it raise exception(with http_proxy and https_proxy set)
```
Running: python polymer_bundler.py (cwd='local')
| App Engine templates are up to date.
Clearing local datastore by removing local/storage.
Created symlink: source: /home/test/clusterfuzz/local/storage/local_gcs, target /home/test/clusterfuzz/src/appengine/local_gcs.
Traceback (most recent call last):
  File "butler.py", line 282, in <module>
    main()
  File "butler.py", line 256, in main
    command.execute(args)
  File "src/local/butler/run_server.py", line 162, in execute
    test_utils.setup_pubsub(constants.TEST_APP_ID)
  File "/home/test/clusterfuzz/src/python/tests/test_libs/test_utils.py", line 308, in setup_pubsub
    _create_pubsub_topic(client, project, queue['name'])
  File "/home/test/clusterfuzz/src/python/tests/test_libs/test_utils.py", line 284, in _create_pubsub_topic
    if client.get_topic(full_name):
  File "/home/test/clusterfuzz/src/python/google_cloud_utils/pubsub.py", line 193, in get_topic
    response = self._execute_with_retry(request)
  File "/home/test/clusterfuzz/src/python/base/retry.py", line 88, in _wrapper
    result = func(*args, **kwargs)
  File "/home/test/clusterfuzz/src/python/google_cloud_utils/pubsub.py", line 108, in _execute_with_retry
    return request.execute()
  File "/home/test/clusterfuzz/src/third_party/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/test/clusterfuzz/src/third_party/googleapiclient/http.py", line 837, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/home/test/clusterfuzz/src/third_party/googleapiclient/http.py", line 162, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/test/clusterfuzz/src/third_party/google_auth_httplib2.py", line 198, in request
    uri, method, body=body, headers=request_headers, **kwargs)
  File "/home/test/clusterfuzz/src/third_party/httplib2/__init__.py", line 1694, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/test/clusterfuzz/src/third_party/httplib2/__init__.py", line 1434, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/test/clusterfuzz/src/third_party/httplib2/__init__.py", line 1390, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

## tried solutions
I updated my goodle cloud sdk to newest, not working.
I unset all my proxy setting `unset http_proxy`, `unset https_proxy`, then rerun a local server, error message shows
```
Running: bower install --allow-root
| bower webcomponentsjs extra-resolution Unnecessary resolution: webcomponentsjs#^v1.0.2
| bower iron-location   extra-resolution Unnecessary resolution: iron-location#1 - 2
| bower mocha           extra-resolution Unnecessary resolution: mocha#^3.1.2
| bower iron-collapse   extra-resolution Unnecessary resolution: iron-collapse#^2.0.0
Traceback (most recent call last):
  File "butler.py", line 282, in <module>
    main()
  File "butler.py", line 256, in main
    command.execute(args)
  File "src/local/butler/run_server.py", line 132, in execute
    common.install_dependencies()
  File "src/local/butler/common.py", line 278, in install_dependencies
    _install_chromedriver()
  File "src/local/butler/common.py", line 185, in _install_chromedriver
    version_request = urllib2.urlopen(constants.CHROMEDRIVER_VERSION_URL)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 101] Network is unreachable>
```

**update**:
I tried start server without install deps
```
python butler.py run_server --skip-install-deps
```
it get stucked
```
Running: pkill -KILL -f "dev_appserver.py"
| Return code is non-zero (-9).
Running: pkill -KILL -f "CloudDatastore.jar"
| Return code is non-zero (-9).
Running: pkill -KILL -f "pubsub-emulator"
| Return code is non-zero (-9).
Created symlink: source: /home/test/clusterfuzz/configs/test, target /home/test/clusterfuzz/src/appengine/config.
Created symlink: source: /home/test/clusterfuzz/configs/test, target /home/test/clusterfuzz/src/go/server/config.
Created symlink: source: /home/test/clusterfuzz/src/protos, target /home/test/clusterfuzz/src/appengine/protos.
Created symlink: source: /home/test/clusterfuzz/src/python, target /home/test/clusterfuzz/src/appengine/python.
Created symlink: source: /home/test/clusterfuzz/src/third_party, target /home/test/clusterfuzz/src/appengine/third_party.
Running: bazel run //local:create_gopath (cwd='src')
| INFO: Invocation ID: ccdb6b13-75dc-4c70-aa3b-ae0fc7f6d447
| Loading:
| Loading: 0 packages loaded
| Analyzing: target //local:create_gopath (0 packages loaded, 0 targets configured)
| INFO: Analysed target //local:create_gopath (0 packages loaded, 0 targets configured).
| INFO: Found 1 target...
| [0 / 1] [-----] BazelWorkspaceStatusAction stable-status.txt
| Target //local:create_gopath up-to-date:
|   bazel-bin/local/create_gopath
| INFO: Elapsed time: 0.243s, Critical Path: 0.00s
| INFO: 0 processes.
| INFO: Build completed successfully, 1 total action
| INFO: Running command line: bazel-bin/local/create_gopath local/gopath
| INFO: Build completed successfully, 1 total action
| /home/test/.cache/bazel/_bazel_test/5d84fedffd4e1a64944d7ddd9fdf1c97/execroot/__main__/bazel-out/k8-fastbuild/bin/local/gopath
Running: python polymer_bundler.py (cwd='local')
| App Engine templates are up to date.
Created symlink: source: /home/test/clusterfuzz/local/storage/local_gcs, target /home/test/clusterfuzz/src/appengine/local_gcs.
```

**Comment by sanqingshan** [comment]
I has meet it,it is because it will access localhost port 9004 9003 9006 and so on when init,so the proxy server must on the same machine with clustfuzz server and igore localhost by proxy rules.

**Comment by inferno-chromium** [comment]
We have a note for this in documentation, see https://google.github.io/clusterfuzz/getting-started/local-instance/#running-a-local-server. list of ports needed are here - https://github.com/google/clusterfuzz/blob/master/src/local/butler/constants.py

"Note: the local instance may use ports other than 9000, such as 9008, for things like uploading files. Therefore, using the local instance may break if the needed ports are unavailable or if you can only access some of the needed ports from your browser (for example: because of port forwarding or firewall rules when accessing from another host)."
