### ISSUE TITLE
Exceptions while writing to log

### ISSUE THREAD

**Issue by hzawawy** [google/clusterfuzz#2288]
During the syzkaller runs, we get a lot of these exceptions. They dont stop the run though.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/handlers.py", line 631, in emit
    s = self.makePickle(record)
  File "/home/shell/clusterfuzz/89JAX004UK/bot/clusterfuzz/src/python/metrics/logs.py", line 226, in makePickle
    return (format_record(record) + '\n').encode('utf-8')
  File "/home/shell/clusterfuzz/89JAX004UK/bot/clusterfuzz/src/python/metrics/logs.py", line 184, in format_record
    return json.dumps(entry)
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

**Comment by inferno-chromium** [comment]
So, this is just failure to log things since some message in log is not serializable. Do you log any output from logs.log, can try removing that and seeing if this goes away.

**Comment by hzawawy** [comment]
This is not a major just littering the logs. I will investigate further and prepare a fix.
