### ISSUE TITLE
cloud build deployment causes exceptions on oss-fuzz deployment 

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#2548]
```
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py", line 21, in <module>
    modules.fix_module_search_paths()
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/base/modules.py", line 77, in fix_module_search_paths
    _patch_appengine_modules_for_bots()
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/base/modules.py", line 40, in _patch_appengine_modules_for_bots
    from google.auth import app_engine as auth_app_engine
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/auth/__init__.py", line 19, in <module>
    from google.auth._default import default
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/auth/_default.py", line 26, in <module>
    import six
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
EOFError: marshal data too short
 
```

**Comment by oliverchang** [comment]
Looks like this only affects a few bad instances which had their disks/filesystem corrupted.
