### ISSUE TITLE
run_server doesn't work with latest setuptools/gcloud sdk

### ISSUE THREAD

**Issue by oliverchang** [google/clusterfuzz#258]
looks like something broke:

```
| ERROR    2019-03-13 01:05:41,541 wsgi.py:263]
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
|     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
|     handler, path, err = LoadObject(self._handler)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
|     obj = __import__(path[0])
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/server.py", line 21, in <module>
|     from handlers import base_handler
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/handlers/base_handler.py", line 34, in <module>
|     from google_cloud_utils import storage
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/python/google_cloud_utils/storage.py", line 39, in <module>
|     from google.cloud import storage as gcs
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/google/cloud/storage/__init__.py", line 36, in <module>
|     __version__ = get_distribution("google-cloud-storage").version
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 481, in get_distribution
|     dist = get_provider(dist)
| INFO     2019-03-13 01:05:41,549 module.py:861] default: "GET /_ah/start HTTP/1.1" 500 -
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 357, in get_provider
|     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 900, in require
|     needed = self.resolve(parse_requirements(requirements))
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 786, in resolve
|     raise DistributionNotFound(req, requirers)
| DistributionNotFound: The 'google-cloud-storage' distribution was not found and is required by the application
| ERROR    2019-03-13 01:05:41,585 wsgi.py:263]
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
|     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
|     handler, path, err = LoadObject(self._handler)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
|     obj = __import__(path[0])
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/server.py", line 21, in <module>
|     from handlers import base_handler
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/handlers/base_handler.py", line 34, in <module>
|     from google_cloud_utils import storage
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/python/google_cloud_utils/storage.py", line 39, in <module>
|     from google.cloud import storage as gcs
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/google/cloud/storage/__init__.py", line 36, in <module>
|     __version__ = get_distribution("google-cloud-storage").version
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 481, in get_distribution
|     dist = get_provider(dist)
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 357, in get_provider
| INFO     2019-03-13 01:05:41,592 module.py:861] default: "GET / HTTP/1.1" 500 -
|     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 900, in require
|     needed = self.resolve(parse_requirements(requirements))
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 786, in resolve
|     raise DistributionNotFound(req, requirers)
| DistributionNotFound: The 'google-cloud-storage' distribution was not found and is required by the application
| ERROR    2019-03-13 01:05:42,708 wsgi.py:263]
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
|     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
|     handler, path, err = LoadObject(self._handler)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
|     obj = __import__(path[0])
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/server.py", line 21, in <module>
|     from handlers import base_handler
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/handlers/base_handler.py", line 34, in <module>
|     from google_cloud_utils import storage
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/python/google_cloud_utils/storage.py", line 39, in <module>
|     from google.cloud import storage as gcs
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/google/cloud/storage/__init__.py", line 36, in <module>
| INFO     2019-03-13 01:05:42,713 module.py:861] default: "GET / HTTP/1.1" 500 -
|     __version__ = get_distribution("google-cloud-storage").version
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 481, in get_distribution
|     dist = get_provider(dist)
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 357, in get_provider
|     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 900, in require
|     needed = self.resolve(parse_requirements(requirements))
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 786, in resolve
|     raise DistributionNotFound(req, requirers)
| DistributionNotFound: The 'google-cloud-storage' distribution was not found and is required by the application
| ERROR    2019-03-13 01:05:43,677 wsgi.py:263]
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
|     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
|     handler, path, err = LoadObject(self._handler)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
|     obj = __import__(path[0])
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/server.py", line 21, in <module>
|     from handlers import base_handler
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/handlers/base_handler.py", line 34, in <module>
|     from google_cloud_utils import storage
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/python/google_cloud_utils/storage.py", line 39, in <module>
|     from google.cloud import storage as gcs
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/google/cloud/storage/__init__.py", line 36, in <module>
|     __version__ = get_distribution("google-cloud-storage").version
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 481, in get_distribution
|     dist = get_provider(dist)
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 357, in get_provider
| INFO     2019-03-13 01:05:43,683 module.py:861] default: "GET / HTTP/1.1" 500 -
|     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 900, in require
|     needed = self.resolve(parse_requirements(requirements))
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 786, in resolve
|     raise DistributionNotFound(req, requirers)
| DistributionNotFound: The 'google-cloud-storage' distribution was not found and is required by the application
| ERROR    2019-03-13 01:05:43,901 wsgi.py:263]
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
|     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
|     handler, path, err = LoadObject(self._handler)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
|     obj = __import__(path[0])
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/server.py", line 21, in <module>
|     from handlers import base_handler
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/handlers/base_handler.py", line 34, in <module>
|     from google_cloud_utils import storage
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/python/google_cloud_utils/storage.py", line 39, in <module>
|     from google.cloud import storage as gcs
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/google/cloud/storage/__init__.py", line 36, in <module>
|     __version__ = get_distribution("google-cloud-storage").version
| INFO     2019-03-13 01:05:43,906 module.py:861] default: "GET / HTTP/1.1" 500 -
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 481, in get_distribution
|     dist = get_provider(dist)
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 357, in get_provider
|     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 900, in require
|     needed = self.resolve(parse_requirements(requirements))
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 786, in resolve
|     raise DistributionNotFound(req, requirers)
| DistributionNotFound: The 'google-cloud-storage' distribution was not found and is required by the application
| INFO     2019-03-13 01:06:13,787 instance.py:294] Instance PID: 204674
| ERROR    2019-03-13 01:06:14,449 wsgi.py:263]
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
|     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
|     handler, path, err = LoadObject(self._handler)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
|     obj = __import__(path[0])
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/server.py", line 21, in <module>
|     from handlers import base_handler
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/handlers/base_handler.py", line 34, in <module>
|     from google_cloud_utils import storage
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/python/google_cloud_utils/storage.py", line 39, in <module>
|     from google.cloud import storage as gcs
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/google/cloud/storage/__init__.py", line 36, in <module>
|     __version__ = get_distribution("google-cloud-storage").version
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 481, in get_distribution
| INFO     2019-03-13 01:06:14,456 module.py:861] cron-service: "GET /_ah/start HTTP/1.1" 500 -
|     dist = get_provider(dist)
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 357, in get_provider
|     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 900, in require
|     needed = self.resolve(parse_requirements(requirements))
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 786, in resolve
|     raise DistributionNotFound(req, requirers)
| DistributionNotFound: The 'google-cloud-storage' distribution was not found and is required by the application
| ERROR    2019-03-13 01:06:14,508 wsgi.py:263]
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
|     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
|     handler, path, err = LoadObject(self._handler)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
|     obj = __import__(path[0])
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/server.py", line 21, in <module>
|     from handlers import base_handler
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/handlers/base_handler.py", line 34, in <module>
|     from google_cloud_utils import storage
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/python/google_cloud_utils/storage.py", line 39, in <module>
|     from google.cloud import storage as gcs
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/google/cloud/storage/__init__.py", line 36, in <module>
|     __version__ = get_distribution("google-cloud-storage").version
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 481, in get_distribution
|     dist = get_provider(dist)
| INFO     2019-03-13 01:06:14,513 module.py:861] cron-service: "GET /triage HTTP/1.1" 500 -
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 357, in get_provider
|     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 900, in require
|     needed = self.resolve(parse_requirements(requirements))
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 786, in resolve
|     raise DistributionNotFound(req, requirers)
| DistributionNotFound: The 'google-cloud-storage' distribution was not found and is required by the application
| ERROR    2019-03-13 01:06:42,809 wsgi.py:263]
| Traceback (most recent call last):
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
|     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
|     handler, path, err = LoadObject(self._handler)
|   File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
|     obj = __import__(path[0])
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/server.py", line 21, in <module>
|     from handlers import base_handler
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/handlers/base_handler.py", line 34, in <module>
|     from google_cloud_utils import storage
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/python/google_cloud_utils/storage.py", line 39, in <module>
|     from google.cloud import storage as gcs
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/google/cloud/storage/__init__.py", line 36, in <module>
|     __version__ = get_distribution("google-cloud-storage").version
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 481, in get_distribution
|     dist = get_provider(dist)
| INFO     2019-03-13 01:06:42,815 module.py:861] cron-service: "GET /cleanup HTTP/1.1" 500 -
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 357, in get_provider
|     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 900, in require
|     needed = self.resolve(parse_requirements(requirements))
|   File "/usr/local/google/home/ochang/clusterfuzz/src/appengine/third_party/pkg_resources/__init__.py", line 786, in resolve
|     raise DistributionNotFound(req, requirers)
| DistributionNotFound: The 'google-cloud-storage' distribution was not found and is required by the application
```

**Comment by oliverchang** [comment]
looks like some sandboxing issue.

getting:

[Errno 13] path not accessible: '/usr/local/google/home/ochang/clusterfuzz/src/python' in pkg_resources.

on https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L2092

```python
def safe_listdir(path):
    """
    Attempt to list contents of path, but suppress some exceptions.
    """
    try:
        return os.listdir(path)
    except (PermissionError, NotADirectoryError):
        pass
    except OSError as e:
        # Ignore the directory if does not exist, not a directory or
        # permission denied
        ignorable = (
            e.errno in (errno.ENOTDIR, errno.EACCES, errno.ENOENT)
            # Python 2 on Windows needs to be handled this way :(
            or getattr(e, "winerror", None) == 267
        )
        if not ignorable:
            raise
    return ()
```

**Comment by oliverchang** [comment]
if I copy the third_party directory instead of symlinking, this works. looks like some behaviour might have changed somewhere with following symlinks.

**Comment by inferno-chromium** [comment]
I think sandbox.py became more restrictive :(

```
+++ b/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/python/runtime/sandbox.py
@@ -80,10 +80,12 @@ _WHITE_LIST_C_MODULES = [
     '_elementtree',
     'errno',
     'exceptions',
+    'fcntl',
     '_fileio',
     '_functools',
     'future_builtins',
     'gc',
+    'grp',
     '_hashlib',
     '_heapq',
     'imp',
@@ -95,6 +97,7 @@ _WHITE_LIST_C_MODULES = [
     '__main__',
     'marshal',
     'math',
+    'mmap',
     '_md5',  # Python2.5 compatibility
     '_multibytecodec',
     'nt',  # Only indirectly through the os module.
@@ -103,8 +106,9 @@ _WHITE_LIST_C_MODULES = [
     'posix',  # Only indirectly through the os module.
     'pyexpat',
     '_random',
-    '_scproxy',  # Mac OS X compatibility
     'select',
+    'spwd',
+    '_scproxy',  # Mac OS X compatibility
     '_sha256',  # Python2.5 compatibility
     '_sha512',  # Python2.5 compatibility
     '_sha',  # Python2.5 compatibility
@@ -947,18 +951,17 @@ class ModuleOverridePolicy(object):
 _MODULE_OVERRIDE_POLICIES = {
     'os': ModuleOverridePolicy(
         default_stub=stubs.os_error_not_implemented,
-        whitelist=['altsep', 'curdir', 'defpath', 'devnull', 'environ', 'error',
-                   'fstat', 'getcwd', 'getcwdu', 'getenv', '_get_exports_list',
-                   'name', 'open', 'pardir', 'path', 'pathsep', 'sep',
-                   'stat_float_times', 'stat_result', 'strerror', 'sys',
-                   'walk'],
+        whitelist=['altsep', 'chown', 'curdir', 'defpath', 'devnull', 'environ',
+                   'error', 'execv', 'fchmod', 'fchown', 'fork', 'fstat',
+                   'ftruncate', 'getcwd', 'getcwdu', 'getenv',
+                   '_get_exports_list', 'kill', 'lchown', 'lstat', 'name',
+                   'open', 'pardir', 'path', 'pathsep', 'readline', 'sep',
+                   'setuid', 'stat', 'stat_float_times', 'stat_result',
+                   'strerror', 'sys', 'waitpid', 'walk', 'readlink'],
         overrides={
             'access': stubs.fake_access,
             'listdir': stubs.RestrictedPathFunction(os.listdir),
-            # Alias lstat() to stat() to match the behavior in production.
-            'lstat': stubs.RestrictedPathFunction(os.stat),
             'open': stubs.fake_open,
-            'stat': stubs.RestrictedPathFunction(os.stat),
             'uname': stubs.fake_uname,
             'getpid': stubs.return_minus_one,
             'getppid': stubs.return_minus_one,
@@ -970,7 +973,7 @@ _MODULE_OVERRIDE_POLICIES = {
             'urandom': stubs.fake_urandom,
             'system': stubs.return_minus_one,
             },
-        deletes=['execv', 'execve']),
+        deletes=['execve']),
     'signal': ModuleOverridePolicy(overrides={'__doc__': None}),
     'locale': ModuleOverridePolicy(
         overrides={'setlocale': stubs.fake_set_locale},
```

**Comment by inferno-chromium** [comment]
Thanks a lot for the quick fix!
