### ISSUE TITLE
Endpoints "/fuzz-strategy-selection" and "/fuzzer-and-job-weights" under cron-service failed. 

### ISSUE THREAD

**Issue by rafalnowicki116** [google/clusterfuzz#2629]
Hi,
Deploy was done from the master, not from the latest tag. 

The reason in both cases is the same:
**"Table afl_stats.TestcaseRun does not have a schema.">. Retrying again.**

Cron-jobs:

Below details for an endpoint "/fuzz-strategy-selection":
![image](https://user-images.githubusercontent.com/60612203/165520715-937f4ed5-3787-4a3c-8100-7d2ef620fbbb.png)

Stacktrace:
```
<HttpError 400 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sta-np-11528163/queries?alt=json returned "Table afl_stats.TestcaseRun does not have a schema.">
Traceback (most recent call last):
  File "/srv/handlers/base_handler.py", line 277, in dispatch_request
    return super(Handler, self).dispatch_request(*args, **kwargs)
  File "third_party/flask/views.py", line 163, in dispatch_request
    return meth(*args, **kwargs)
  File "/srv/libs/handler.py", line 100, in wrapper
    result = func(self)
  File "/srv/handlers/cron/fuzz_strategy_selection.py", line 218, in get
    _query_and_upload_strategy_probabilities(engine)
  File "/srv/handlers/cron/fuzz_strategy_selection.py", line 185, in _query_and_upload_strategy_probabilities
    data = _query_multi_armed_bandit_probabilities(engine)
  File "/srv/handlers/cron/fuzz_strategy_selection.py", line 151, in _query_multi_armed_bandit_probabilities
    return client.query(query=formatted_query).rows
  File "/srv/clusterfuzz/_internal/google_cloud_utils/big_query.py", line 247, in query
    result = self.raw_query(query, max_results=0)
  File "/srv/clusterfuzz/_internal/base/retry.py", line 88, in _wrapper
    result = func(*args, **kwargs)
  File "/srv/clusterfuzz/_internal/google_cloud_utils/big_query.py", line 190, in raw_query
    projectId=self.project_id, body=body).execute()
  File "third_party/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "third_party/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/sta-np-11528163/queries?alt=json returned "Table afl_stats.TestcaseRun does not have a schema.">
```

**Is it normal behaviour?**

**Do you have any idea what can be wrong? How to fix it?**

So far we have only tested libfuzzer, afl wasn't touched yet.

Thanks,

**Comment by urbanenomad** [comment]
Were you able to get this fixed?  We get the same error.  Could we just copy the schema from a different fuzzer?

**Comment by urbanenomad** [comment]
Or can we just directly delete the bigquery dataset for the ones that do not have a schema?  Is there a proper way to do this?

**Comment by oliverchang** [comment]
Thanks for the report! I have a fix uploaded at https://github.com/google/clusterfuzz/pull/2642.  Once that's merged, you'll need to delete the existing afl tables in BigQuery for the fix to take effect. 

Note however that if you're only running libFuzzer, this error is harmless, as the libFuzzer analysis should run and completely successful first before reaching afl.

**Comment by rafalnowicki116** [comment]
> 
That is correct, I was able to observe that libfuzzer is working correctly. Thanks for the fix.
