### ISSUE TITLE
error deploying version 2.5.7

### ISSUE THREAD

**Issue by quanyangsc** [google/clusterfuzz#2649]
This is with python 3.7 on v2.5.7. 

Trace:
```Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/opt/python3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/main.py", line 42, in <module>
    import server
  File "/srv/server.py", line 19, in <module>
    from google.cloud import ndb
  File "third_party/google/cloud/ndb/__init__.py", line 28, in <module>
    from google.cloud.ndb.client import Client
  File "third_party/google/cloud/ndb/client.py", line 18, in <module>
    import grpc
  File "third_party/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (third_party/grpc/_cython/__init__.py)```

**Comment by oliverchang** [comment]
Hi there! 

We haven't seen this before, but usually I've seen this in the past if there's a mismatch in the Python version used for `python butler.py bootstrap` (which vendors the depenencies) and the one used for deploy. 

Are you deploying with Python 3.7 as well?

**Comment by quanyangsc** [comment]
> Hi there!
> 
> We haven't seen this before, but usually I've seen this in the past if there's a mismatch in the Python version used for for deployment vs the actual production environment.
> 
> Are you deploying with Python 3.7 as well as using the same version in production

Yes,  this is deployed with 3.7, I also tried with 3.8/3.9 but got the same errors. What's odd is that I can deploy a previous version without any issues using the same environment.

**Comment by oliverchang** [comment]
Do unit tests work locally? Does `cygrpc.cpython-37m-x86_64-linux-gnu.so` exist in `src/third_party/grpc/_cython` ?

**Comment by quanyangsc** [comment]
> Do unit tests work locally? 

The unit tests mostly works except for `test_profiler (tests.core.metrics.profiler_test.ProfilerTest)`
```
ImportError: cannot import name '_profiler' from 'googlecloudprofiler' (./clusterfuzz/src/third_party/googlecloudprofiler/__init__.py)
```
> Does `cygrpc.cpython-37m-x86_64-linux-gnu.so` exist in `src/third_party/grpc/_cython` ?
It exists within `deployment/linux-3.zip`, but it also contains the darwin version of it `cygrpc.cpython-37m-darwin.so`.

**Comment by oliverchang** [comment]
That's really strange -- we definitely are not able to reproduce this. 

The main change we made (that I can think of) which may affect this is https://github.com/google/clusterfuzz/commit/fb88290102f60c6ddcb3c5b38ea21d360f207b5f.

Would you be able to check if this is what's causing the issues for you?

**Comment by quanyangsc** [comment]
After some testing, the issue seems to be related to naming the appengine requirements file `gae_requirements.txt` instead of `requirements.txt`, any idea why that'd matter?

**Comment by oliverchang** [comment]
I believe `gcloud app deploy` understands and uses `requirements.txt`, while we did not want this and installed/vendored our own third_party dependencies. 

So this definitely works if you just rename the `gae_requirements.txt` file to `requirements.txt` ?

We can experiment to see if we can just use `requirements.txt` for all App Engine deployments.

**Comment by quanyangsc** [comment]
I took another look, and I believe the root cause is indeed due to the lack of `cygrpc.cpython-37m-x86_64-linux-gnu.so` in `src/appengine/third_party` while deploying from Mac OS. Seems like previously the issue was avoided as appengine was installing dependencies from `requirements.txt` and not using what's in third_party possibly.

So for deployment to work from a non-linux it seems like we'd have to download the linux version of grpcio into `third_party`

**Comment by oliverchang** [comment]
I see! Yes -- deployment was intended to only be supported from Linux. Sadly none of us use macOS for development so that path is not well tested.

**Comment by oliverchang** [comment]
We can take a look into if can just use `requirements.txt` directly without trying to install the dependencies ourselves.

**Comment by quanyangsc** [comment]
> I believe `gcloud app deploy` understands and uses `requirements.txt`, while we did not want this and installed/vendored our own third_party dependencies.
> 
> So this definitely works if you just rename the `gae_requirements.txt` file to `requirements.txt` ?
> 
> We can experiment to see if we can just use `requirements.txt` for all App Engine deployments.

I believe requirements.txt would work, but there are some additional dependencies that needed to be pinned like werkzeug and pyparsing

**Comment by oliverchang** [comment]
I uploaded https://github.com/google/clusterfuzz/pull/2661 for this.

**Comment by quanyangsc** [comment]
The commit fixes the cygrpc issue but results in a different issue with dependencies:

```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/opt/python3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/srv/main.py", line 42, in <module>
    import server
  File "/srv/server.py", line 16, in <module>
    from flask import Flask
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 32, in <module>
    from werkzeug.wrappers import BaseResponse
ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' (/layers/google.python.pip/pip/lib/python3.7/site-packages/werkzeug/wrappers/__init__.py)
```

The fix for this is to either:
1. update flask to a newer version >= 2.0
2. pin flask to 1.1.4 (which requires downgrading other dependencies that flask uses like itsdangerous)
3. pinning werkzeug to 2.0.3

I made a PR for pinning werkzeug at https://github.com/google/clusterfuzz/pull/2671
