### ISSUE TITLE
pipenv lock -r command seems to fail when running butler.py bootstrap

### ISSUE THREAD

**Issue by davfu1** [google/clusterfuzz#2952]
https://github.com/google/clusterfuzz/blob/57073e10e76726c1e8a57ef75d3dadd80cf3d85e/src/local/butler/common.py#L250

Initial dependency installation runs `python -m pipenv lock -r --noheader` to generate requirements.txt files in `/src/` and `/src/appengine`. 

It seems `pipenv lock -r`, is replaced with `pipenv requirements > requirements.txt` in newer versions of pipenv (I am running version 2023.2.18). I unblocked myself by manually running the new command.

Additional context: https://github.com/serverless-stack/sst/issues/1954

**Comment by oliverchang** [comment]
Per https://github.com/google/clusterfuzz/blob/57073e10e76726c1e8a57ef75d3dadd80cf3d85e/src/local/butler/common.py#L242

We actually try running `pipenv requirements` first, and if that fails, we run `pipenv lock` as a fallback.

Are you able to paste the output of the failing  `pipenv requirements`  command?

**Comment by davfu1** [comment]
Ah - I've realized now that the pipenv shell environment has its own, older version of pipenv (2022.1.8) which should have still recognized line 250's `pipenv lock -r` command. So the problem seems to be in execution of the command, not the pipenv version as I suggested earlier.

In the shell environment, manually executing `pipenv lock -r` does print the expected requirements file when used in terminal. But `pipenv lock -r` fails when being called by execute() in `python butler.py bootstrap`: the subprocess.popen() library used to run `pipenv lock -r` returns non-zero. Thus, no requirements file is generated under the older version of pipenv (2022.1.8) using `pipenv lock -r`.

**Comment by oliverchang** [comment]
Friendly ping @davfu1. Are you still running into this?

**Comment by davfu1** [comment]
Hi Oliver - thanks so much for checking on this! I wasn't sure whether to pursue the issue as I was able to unblock myself by manually creating `requirements.txt` files in `clusterfuzz/src` and `clusterfuzz/src/appengine`.

However, I did try running the script again in a fresh environment (with Python 3.10.9) and ran into the same error. Following your suggestion of removing line 254, I did see the logs,

```
Running: python -m pipenv lock -r --no-header  (cwd='src')
| Creating a virtualenv for this project...
| Pipfile: /usr/local/google/home/davfu/clusterfuzz-test/clusterfuzz/src/Pipfile
| Using /usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/bin/python (3.10.9) to create virtualenv...
⠦ Creating virtual environment...created virtual environment CPython3.10.9.final.0-64 in 258ms
|   creator CPython3Posix(dest=/usr/local/google/home/davfu/.local/share/virtualenvs/src-kDFYsB6q, clear=False, no_vcs_ignore=False, global=False)
|   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/usr/local/google/home/davfu/.local/share/virtualenv)
|     added seed packages: pip==22.3.1, setuptools==65.6.3, wheel==0.38.4
|   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
| 
|✔ Successfully created virtual environment!
| Traceback (most recent call last):
|   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
|     return _run_code(code, main_globals, None,
|   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
|     exec(code, run_globals)
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/__main__.py", line 5, in <module>
|     cli()
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
|     return self.main(*args, **kwargs)
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1053, in main
|     rv = self.invoke(ctx)
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
|     return _process_result(sub_ctx.command.invoke(sub_ctx))
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
|     return ctx.invoke(self.callback, **ctx.params)
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
|     return __callback(*args, **kwargs)
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
|     return ctx.invoke(f, obj, *args, **kwargs)
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
|     return __callback(*args, **kwargs)
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 26, in new_func
|     return f(get_current_context(), *args, **kwargs)
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/cli/command.py", line 296, in lock
|     ensure_project(
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/core.py", line 526, in ensure_project
|     ensure_virtualenv(
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/core.py", line 465, in ensure_virtualenv
|     do_create_virtualenv(
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/core.py", line 945, in do_create_virtualenv
|     project._environment = Environment(
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/environment.py", line 72, in __init__
|     self._base_paths = self.get_paths()
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/environment.py", line 360, in get_paths
|     c = subprocess_run(command)
|   File "/usr/local/google/home/davfu/.local/share/virtualenvs/clusterfuzz-GT7QmMun/lib/python3.10/site-packages/pipenv/utils.py", line 2326, in subprocess_run
|     return subprocess.run(
|   File "/usr/lib/python3.10/subprocess.py", line 503, in run
|     with Popen(*popenargs, **kwargs) as process:
|   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
|     self._execute_child(args, executable, preexec_fn, close_fds,
|   File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
|     raise child_exception_type(errno_num, err_msg, err_filename)
| FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/google/home/davfu/.local/share/virtualenvs/src-kDFYsB6q/bin/python'
| Return code is non-zero (1).
Traceback (most recent call last):
  File "/usr/local/google/home/davfu/clusterfuzz-test/clusterfuzz/butler.py", line 273, in <module>
    main()
  File "/usr/local/google/home/davfu/clusterfuzz-test/clusterfuzz/butler.py", line 259, in main
    command.execute(args)
  File "/usr/local/google/home/davfu/clusterfuzz-test/clusterfuzz/src/local/butler/bootstrap.py", line 25, in execute
    common.install_dependencies()
  File "/usr/local/google/home/davfu/clusterfuzz-test/clusterfuzz/src/local/butler/common.py", line 325, in install_dependencies
    _pipfile_to_requirements('src', 'src/requirements.txt')
  File "/usr/local/google/home/davfu/clusterfuzz-test/clusterfuzz/src/local/butler/common.py", line 256, in _pipfile_to_requirements
    raise Exception('Failed to generate requirements from Pipfile.')
Exception: Failed to generate requirements from Pipfile.
```

**Comment by oliverchang** [comment]
Does this still happen for you after https://github.com/google/clusterfuzz/commit/4af2b87e3fc336233d8829fccacbb840d68d30a5 ?

**Comment by davfu1** [comment]
The `install_deps` script no longer errors out for me - seems the fix has worked!

**Comment by oliverchang** [comment]
Nice! This is thanks to @hogo6002 and @Alan32Liu :)
