### ISSUE TITLE
Centipede stats breaking fuzzing in chrome clusterfuzz

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#3109]
```
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py", line 95, in task_loop
    commands.process_command(task)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/commands.py", line 227, in wrapper
    return func(task)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/commands.py", line 466, in process_command
    run_command(task_name, task_argument, job_name, uworker_env)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/commands.py", line 281, in run_command
    task.execute(task_argument, job_name, uworker_env)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/commands.py", line 65, in execute
    self.module.execute_task(task_argument, job_type)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/fuzz_task.py", line 1915, in execute_task
    session.run()
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/fuzz_task.py", line 1838, in run
    crashes, fuzzer_metadata = self.do_engine_fuzzing(engine_impl)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/fuzz_task.py", line 1544, in do_engine_fuzzing
    result.command)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/fuzzers/engine_common.py", line 251, in get_testcase_run
    testcase_run.update(stats)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/metrics/fuzzer_stats.py", line 143, in update
    self._stats_data.update(other)
TypeError: 'NoneType' object is not iterable
```

**Comment by Alan32Liu** [comment]
I don't think `Centipede` does not support stats report yet.

**Comment by jonathanmetzman** [comment]
It appears that this isn't an issue in oss-fuzz, but for some reason there are never any logs from centipede fuzzing runs (try `gsutil -m ls gs://skcms-logs.clusterfuzz-external.appspot.com` on any project where centipede is enabled).
I think in chrome clusterfuzz, fuzzing with centipede is happening but some post-fuzzing stuff (I think even syncing corpus back) is broken.

**Comment by jonathanmetzman** [comment]
Fixed this.
