### ISSUE TITLE
GCE Instances Exceeding Memory

### ISSUE THREAD

**Issue by marktefftech** [google/clusterfuzz#3280]
Since 07-20-2023 the memory handling on GCE (Cuttlefish x86) instances is no longer working as expected, and all bots in our environment are hitting the following error (full log attached):

```
OSError: [Errno 28] No space left on device
2023-08-09 17:24:44,394 - run_bot - ERROR - Task exited with exception
```

Bumping the disk size from 100 -> 115GB in the config file does not appear to have resolved the issue:

```
 diskSizeGb: 115
```

**Comment by marktefftech** [comment]
```
2023-08-09 17:01:50,744 - run_bot - INFO - Checking source code for updates.
2023-08-09 17:01:50,813 - run_bot - INFO - Local source code version: 20230809162027-utc-2573bcb-metzman.
2023-08-09 17:01:50,814 - run_bot - INFO - Remote source code version: 20230809162027-utc-2573bcb-metzman.
2023-08-09 17:01:50,814 - run_bot - INFO - Remote souce code <= local source code. No update.
2023-08-09 17:01:50,814 - run_bot - INFO - Running platform initialization scripts.
2023-08-09 17:01:50,816 - run_bot - INFO - Set cuttlefish device serial: 172.18.0.2:6520
2023-08-09 17:02:07,699 - run_bot - INFO - Downloading artifact cf_x86_64_phone-img-10633722.zip.
2023-08-09 17:02:08,052 - run_bot - INFO - 0.8% complete.
2023-08-09 17:02:08,478 - run_bot - INFO - 1.7% complete.
2023-08-09 17:02:08,899 - run_bot - INFO - 2.5% complete.
2023-08-09 17:02:09,330 - run_bot - INFO - 3.4% complete.
2023-08-09 17:02:09,713 - run_bot - INFO - 4.2% complete.
2023-08-09 17:02:10,155 - run_bot - INFO - 5.1% complete.
2023-08-09 17:02:10,649 - run_bot - INFO - 5.9% complete.
2023-08-09 17:02:11,096 - run_bot - INFO - 6.8% complete.
2023-08-09 17:02:11,578 - run_bot - INFO - 7.6% complete.
2023-08-09 17:02:11,979 - run_bot - INFO - 8.5% complete.
2023-08-09 17:02:12,369 - run_bot - INFO - 9.3% complete.
2023-08-09 17:02:12,821 - run_bot - INFO - 10.1% complete.
2023-08-09 17:02:13,270 - run_bot - INFO - 11.0% complete.
2023-08-09 17:02:13,819 - run_bot - INFO - 11.8% complete.
2023-08-09 17:02:14,227 - run_bot - INFO - 12.7% complete.
2023-08-09 17:02:14,620 - run_bot - INFO - 13.5% complete.
2023-08-09 17:02:15,054 - run_bot - INFO - 14.4% complete.
2023-08-09 17:02:15,472 - run_bot - INFO - 15.2% complete.
2023-08-09 17:02:15,934 - run_bot - INFO - 16.1% complete.
2023-08-09 17:02:16,302 - run_bot - INFO - 16.9% complete.
2023-08-09 17:02:16,705 - run_bot - INFO - 17.8% complete.
2023-08-09 17:02:17,160 - run_bot - INFO - 18.6% complete.
2023-08-09 17:02:17,541 - run_bot - INFO - 19.4% complete.
2023-08-09 17:02:17,970 - run_bot - INFO - 20.3% complete.
2023-08-09 17:02:18,401 - run_bot - INFO - 21.1% complete.
2023-08-09 17:02:18,834 - run_bot - INFO - 22.0% complete.
2023-08-09 17:02:19,210 - run_bot - INFO - 22.8% complete.
2023-08-09 17:02:19,687 - run_bot - INFO - 23.7% complete.
2023-08-09 17:02:20,081 - run_bot - INFO - 24.5% complete.
2023-08-09 17:02:20,477 - run_bot - INFO - 25.4% complete.
2023-08-09 17:02:20,943 - run_bot - INFO - 26.2% complete.
2023-08-09 17:02:21,312 - run_bot - INFO - 27.1% complete.
2023-08-09 17:02:21,744 - run_bot - INFO - 27.9% complete.
2023-08-09 17:02:22,156 - run_bot - INFO - 28.7% complete.
2023-08-09 17:02:22,681 - run_bot - INFO - 29.6% complete.
2023-08-09 17:02:23,123 - run_bot - INFO - 30.4% complete.
2023-08-09 17:02:23,558 - run_bot - INFO - 31.3% complete.
2023-08-09 17:02:24,163 - run_bot - INFO - 32.1% complete.
2023-08-09 17:02:24,540 - run_bot - INFO - 33.0% complete.
2023-08-09 17:02:24,949 - run_bot - INFO - 33.8% complete.
2023-08-09 17:02:25,352 - run_bot - INFO - 34.7% complete.
2023-08-09 17:02:25,728 - run_bot - INFO - 35.5% complete.
2023-08-09 17:02:26,119 - run_bot - INFO - 36.4% complete.
2023-08-09 17:02:26,577 - run_bot - INFO - 37.2% complete.
2023-08-09 17:02:27,039 - run_bot - INFO - 38.0% complete.
2023-08-09 17:02:27,451 - run_bot - INFO - 38.9% complete.
2023-08-09 17:02:27,870 - run_bot - INFO - 39.7% complete.
2023-08-09 17:02:28,241 - run_bot - INFO - 40.6% complete.
2023-08-09 17:02:28,732 - run_bot - INFO - 41.4% complete.
2023-08-09 17:02:29,147 - run_bot - INFO - 42.3% complete.
2023-08-09 17:02:29,551 - run_bot - INFO - 43.1% complete.
2023-08-09 17:02:29,940 - run_bot - INFO - 44.0% complete.
2023-08-09 17:02:30,324 - run_bot - INFO - 44.8% complete.
2023-08-09 17:02:30,857 - run_bot - INFO - 45.7% complete.
2023-08-09 17:02:31,287 - run_bot - INFO - 46.5% complete.
2023-08-09 17:02:31,726 - run_bot - INFO - 47.3% complete.
2023-08-09 17:02:32,161 - run_bot - INFO - 48.2% complete.
2023-08-09 17:02:32,605 - run_bot - INFO - 49.0% complete.
2023-08-09 17:02:32,992 - run_bot - INFO - 49.9% complete.
2023-08-09 17:02:33,395 - run_bot - INFO - 50.7% complete.
2023-08-09 17:02:33,835 - run_bot - INFO - 51.6% complete.
2023-08-09 17:02:34,244 - run_bot - INFO - 52.4% complete.
2023-08-09 17:02:34,665 - run_bot - INFO - 53.3% complete.
2023-08-09 17:02:35,019 - run_bot - INFO - 54.1% complete.
2023-08-09 17:02:35,374 - run_bot - INFO - 55.0% complete.
2023-08-09 17:02:35,791 - run_bot - INFO - 55.8% complete.
2023-08-09 17:02:36,200 - run_bot - INFO - 56.6% complete.
2023-08-09 17:02:36,580 - run_bot - INFO - 57.5% complete.
2023-08-09 17:02:37,037 - run_bot - INFO - 58.3% complete.
2023-08-09 17:02:37,456 - run_bot - INFO - 59.2% complete.
2023-08-09 17:02:37,889 - run_bot - INFO - 60.0% complete.
2023-08-09 17:02:38,283 - run_bot - INFO - 60.9% complete.
2023-08-09 17:02:38,640 - run_bot - INFO - 61.7% complete.
2023-08-09 17:02:39,116 - run_bot - INFO - 62.6% complete.
2023-08-09 17:02:39,503 - run_bot - INFO - 63.4% complete.
2023-08-09 17:02:39,932 - run_bot - INFO - 64.3% complete.
2023-08-09 17:02:40,349 - run_bot - INFO - 65.1% complete.
2023-08-09 17:02:40,765 - run_bot - INFO - 65.9% complete.
2023-08-09 17:02:41,178 - run_bot - INFO - 66.8% complete.
2023-08-09 17:02:41,587 - run_bot - INFO - 67.6% complete.
2023-08-09 17:02:42,138 - run_bot - INFO - 68.5% complete.
2023-08-09 17:02:42,556 - run_bot - INFO - 69.3% complete.
2023-08-09 17:02:42,996 - run_bot - INFO - 70.2% complete.
2023-08-09 17:02:43,461 - run_bot - INFO - 71.0% complete.
2023-08-09 17:02:43,978 - run_bot - INFO - 71.9% complete.
2023-08-09 17:02:44,352 - run_bot - INFO - 72.7% complete.
2023-08-09 17:02:44,730 - run_bot - INFO - 73.6% complete.
2023-08-09 17:02:45,271 - run_bot - INFO - 74.4% complete.
2023-08-09 17:02:45,709 - run_bot - INFO - 75.2% complete.
2023-08-09 17:02:46,168 - run_bot - INFO - 76.1% complete.
2023-08-09 17:02:46,560 - run_bot - INFO - 76.9% complete.
2023-08-09 17:02:46,960 - run_bot - INFO - 77.8% complete.
2023-08-09 17:02:47,494 - run_bot - INFO - 78.6% complete.
2023-08-09 17:02:47,898 - run_bot - INFO - 79.5% complete.
2023-08-09 17:02:48,295 - run_bot - INFO - 80.3% complete.
2023-08-09 17:02:48,652 - run_bot - INFO - 81.2% complete.
2023-08-09 17:02:49,107 - run_bot - INFO - 82.0% complete.
2023-08-09 17:02:49,490 - run_bot - INFO - 82.9% complete.
2023-08-09 17:02:49,977 - run_bot - INFO - 83.7% complete.
2023-08-09 17:02:50,389 - run_bot - INFO - 84.5% complete.
2023-08-09 17:02:50,767 - run_bot - INFO - 85.4% complete.
2023-08-09 17:02:51,159 - run_bot - INFO - 86.2% complete.
2023-08-09 17:02:51,568 - run_bot - INFO - 87.1% complete.
2023-08-09 17:02:51,983 - run_bot - INFO - 87.9% complete.
2023-08-09 17:02:52,373 - run_bot - INFO - 88.8% complete.
2023-08-09 17:02:52,757 - run_bot - INFO - 89.6% complete.
2023-08-09 17:02:53,163 - run_bot - INFO - 90.5% complete.
2023-08-09 17:02:53,603 - run_bot - INFO - 91.3% complete.
2023-08-09 17:02:54,008 - run_bot - INFO - 92.2% complete.
2023-08-09 17:02:54,469 - run_bot - INFO - 93.0% complete.
2023-08-09 17:02:54,849 - run_bot - INFO - 93.8% complete.
2023-08-09 17:02:55,191 - run_bot - INFO - 94.7% complete.
2023-08-09 17:02:55,579 - run_bot - INFO - 95.5% complete.
2023-08-09 17:02:55,951 - run_bot - INFO - 96.4% complete.
2023-08-09 17:02:56,379 - run_bot - INFO - 97.2% complete.
2023-08-09 17:02:56,787 - run_bot - INFO - 98.1% complete.
2023-08-09 17:02:57,237 - run_bot - INFO - 98.9% complete.
2023-08-09 17:02:57,632 - run_bot - INFO - 99.8% complete.
2023-08-09 17:02:57,945 - run_bot - INFO - 100.0% complete.
2023-08-09 17:02:58,110 - run_bot - INFO - Downloading artifact licensetexts/cf_x86_64_phone-img-10633722.zip.txt.
2023-08-09 17:02:58,111 - run_bot - INFO - Creating directory /mnt/scratch0/clusterfuzz/bot/inputs/images/licensetexts
2023-08-09 17:02:58,316 - run_bot - INFO - 100.0% complete.
2023-08-09 17:02:58,466 - run_bot - INFO - Downloading artifact shareprojects/cf_x86_64_phone-img-10633722.zip.shareprojects.
2023-08-09 17:02:58,466 - run_bot - INFO - Creating directory /mnt/scratch0/clusterfuzz/bot/inputs/images/shareprojects
2023-08-09 17:02:58,672 - run_bot - INFO - 100.0% complete.
2023-08-09 17:03:55,665 - run_bot - INFO - Unpacked 11/11.
2023-08-09 17:04:56,873 - run_bot - INFO - Downloading artifact cvd-host_package.tar.gz.
2023-08-09 17:04:57,462 - run_bot - INFO - 3.5% complete.
2023-08-09 17:04:57,862 - run_bot - INFO - 7.0% complete.
2023-08-09 17:04:58,260 - run_bot - INFO - 10.5% complete.
2023-08-09 17:04:58,658 - run_bot - INFO - 14.0% complete.
2023-08-09 17:04:59,188 - run_bot - INFO - 17.5% complete.
2023-08-09 17:04:59,562 - run_bot - INFO - 21.0% complete.
2023-08-09 17:04:59,970 - run_bot - INFO - 24.5% complete.
2023-08-09 17:05:00,389 - run_bot - INFO - 28.0% complete.
2023-08-09 17:05:00,778 - run_bot - INFO - 31.6% complete.
2023-08-09 17:05:01,167 - run_bot - INFO - 35.1% complete.
2023-08-09 17:05:01,588 - run_bot - INFO - 38.6% complete.
2023-08-09 17:05:02,061 - run_bot - INFO - 42.1% complete.
2023-08-09 17:05:02,467 - run_bot - INFO - 45.6% complete.
2023-08-09 17:05:02,903 - run_bot - INFO - 49.1% complete.
2023-08-09 17:05:03,401 - run_bot - INFO - 52.6% complete.
2023-08-09 17:05:03,869 - run_bot - INFO - 56.1% complete.
2023-08-09 17:05:04,312 - run_bot - INFO - 59.6% complete.
2023-08-09 17:05:04,728 - run_bot - INFO - 63.1% complete.
2023-08-09 17:05:05,205 - run_bot - INFO - 66.6% complete.
2023-08-09 17:05:05,694 - run_bot - INFO - 70.1% complete.
2023-08-09 17:05:06,106 - run_bot - INFO - 73.6% complete.
2023-08-09 17:05:06,673 - run_bot - INFO - 77.1% complete.
2023-08-09 17:05:07,041 - run_bot - INFO - 80.6% complete.
2023-08-09 17:05:07,560 - run_bot - INFO - 84.1% complete.
2023-08-09 17:05:08,922 - run_bot - INFO - 87.7% complete.
2023-08-09 17:05:10,246 - run_bot - INFO - 91.2% complete.
2023-08-09 17:05:10,637 - run_bot - INFO - 94.7% complete.
2023-08-09 17:05:11,030 - run_bot - INFO - 98.2% complete.
2023-08-09 17:05:11,993 - run_bot - INFO - 100.0% complete.
2023-08-09 17:05:44,078 - run_bot - INFO - Reimaging cuttlefish device.
2023-08-09 17:05:46,610 - run_bot - WARNING - ssh -o StrictHostKeyChecking=no vsoc-01@172.18.0.2 "/home/vsoc-01/bin/stop_cvd" returned 127 error code.
NoneType: None
2023-08-09 17:16:48,768 - run_bot - INFO - Connect to cuttlefish device.
2023-08-09 17:16:48,922 - run_bot - INFO - Reimaging finished.
2023-08-09 17:16:49,231 - run_bot - INFO - Connect to cuttlefish device.
2023-08-09 17:16:52,206 - run_bot - INFO - Completed running platform initialization scripts.
2023-08-09 17:16:55,141 - run_bot - INFO - Executing command "fuzz libFuzzer libfuzzer_asan_android_device"
2023-08-09 17:17:00,651 - run_bot - INFO - Process kill took longer than usual - 0:00:05.
2023-08-09 17:17:06,136 - run_bot - INFO - Starting utask_preprocess: <module 'clusterfuzz._internal.bot.tasks.utasks.fuzz_task' from '/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/fuzz_task.py'>.
2023-08-09 17:17:06,615 - run_bot - INFO - Starting utask_main: <module 'clusterfuzz._internal.bot.tasks.utasks.fuzz_task' from '/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/fuzz_task.py'>.
2023-08-09 17:17:06,617 - run_bot - INFO - Setting up fuzzer and data bundles.
2023-08-09 17:17:10,944 - run_bot - INFO - Picked fuzz target mediaplayer_fuzzer for fuzzing.
2023-08-09 17:17:11,992 - run_bot - INFO - Retrieving build r10633159.
2023-08-09 17:17:12,267 - run_bot - INFO - Removing build directory /mnt/scratch0/clusterfuzz/bot/builds/android-haiku_target-cuttlefish_asan_mediaplayer_fuzzer_77651789446b3c3a04b9f492ff141f003d437347/revisions.
2023-08-09 17:17:12,751 - run_bot - INFO - Downloading build from url gs://android-haiku/target-cuttlefish/asan/mediaplayer_fuzzer/10633159.zip.
2023-08-09 17:17:19,784 - run_bot - INFO - Unpacking build archive /mnt/scratch0/clusterfuzz/bot/builds/android-haiku_target-cuttlefish_asan_mediaplayer_fuzzer_77651789446b3c3a04b9f492ff141f003d437347/revisions/10633159.zip.
2023-08-09 17:18:24,002 - run_bot - INFO - Unpacked 177/177.
2023-08-09 17:18:24,005 - run_bot - INFO - Use previously picked fuzz target mediaplayer_fuzzer for fuzzing.
2023-08-09 17:18:24,030 - run_bot - INFO - Build took 1.20 minutes to unpack.
2023-08-09 17:18:24,034 - run_bot - INFO - Retrieved build r10633159.
2023-08-09 17:18:24,036 - run_bot - INFO - Setup application path.
2023-08-09 17:18:24,198 - run_bot - INFO - Checking for bad build.
2023-08-09 17:18:24,725 - run_bot - INFO - Recorded use of fuzz target libFuzzer_android_mediaplayer_fuzzer.
2023-08-09 17:20:17,478 - run_bot - ERROR - Retrying on google_cloud_utils.storage.copy_file_from failed with [Errno 28] No space left on device. Raise.
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/base/retry.py", line 110, in _wrapper
    result = func(*args, **kwargs)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/google_cloud_utils/storage.py", line 873, in copy_file_from
    if not _provider().copy_file_from(cloud_storage_file_path, local_file_path):
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/google_cloud_utils/storage.py", line 233, in copy_file_from
    blob.download_to_filename(local_path)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/storage/blob.py", line 1200, in download_to_filename
    checksum=checksum,
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/storage/client.py", line 728, in download_blob_to_file
    checksum=checksum,
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/storage/blob.py", line 961, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/resumable_media/requests/download.py", line 171, in consume
    self._write_to_stream(result)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/resumable_media/requests/download.py", line 106, in _write_to_stream
    self._stream.write(chunk)
OSError: [Errno 28] No space left on device
2023-08-09 17:20:22,250 - run_bot - ERROR - Error occurred while working on task.
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py", line 99, in task_loop
    commands.process_command(task)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/commands.py", line 160, in wrapper
    return func(task)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/commands.py", line 398, in process_command
    run_command(task_name, task_argument, job_name, uworker_env)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/commands.py", line 213, in run_command
    task.execute(task_argument, job_name, uworker_env)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/task_types.py", line 84, in execute
    uworker_output = utasks.uworker_main_no_io(self.module, uworker_input)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/__init__.py", line 48, in uworker_main_no_io
    uworker_output = utask_module.utask_main(uworker_input)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/fuzz_task.py", line 1925, in utask_main
    return session.run()
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/fuzz_task.py", line 1827, in run
    crashes, fuzzer_metadata = self.do_engine_fuzzing(engine_impl)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/fuzz_task.py", line 1527, in do_engine_fuzzing
    self.sync_corpus(sync_corpus_directory)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/fuzz_task.py", line 1319, in sync_corpus
    if not self.gcs_corpus.sync_from_gcs():
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/fuzz_task.py", line 530, in sync_from_gcs
    self._corpus_directory)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/fuzzing/corpus_manager.py", line 587, in rsync_to_disk
    result = super().rsync_to_disk(directory, timeout=timeout, delete=delete)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/fuzzing/corpus_manager.py", line 362, in rsync_to_disk
    self.download_zipcorpora(directory)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/fuzzing/corpus_manager.py", line 335, in download_zipcorpora
    if not storage.copy_file_from(zipcorpus_url, temp_zip_filename):
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/base/retry.py", line 110, in _wrapper
    result = func(*args, **kwargs)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/google_cloud_utils/storage.py", line 873, in copy_file_from
    if not _provider().copy_file_from(cloud_storage_file_path, local_file_path):
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/google_cloud_utils/storage.py", line 233, in copy_file_from
    blob.download_to_filename(local_path)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/storage/blob.py", line 1200, in download_to_filename
    checksum=checksum,
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/storage/client.py", line 728, in download_blob_to_file
    checksum=checksum,
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/storage/blob.py", line 961, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/resumable_media/requests/download.py", line 171, in consume
    self._write_to_stream(result)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/resumable_media/requests/download.py", line 106, in _write_to_stream
    self._stream.write(chunk)
OSError: [Errno 28] No space left on device
2023-08-09 17:24:44,394 - run_bot - ERROR - Task exited with exception (payload="fuzz libFuzzer libfuzzer_asan_android_device").
NoneType: None
2023-08-09 17:24:44,394 - run_bot - INFO - Start hanging forever.
```

**Comment by jonathanmetzman** [comment]
I think we fixed this.

**Comment by marktefftech** [comment]
+1 resolved
