### ISSUE TITLE
Fix privileged operation in variant

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#3876]
```
"Error occurred while working on task.
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/_datastore_api.py", line 93, in rpc_call
    result = yield rpc
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.PERMISSION_DENIED
	details = "Missing or insufficient permissions."
	debug_error_string = "{"created":"@1710638457.170821020","description":"Error received from peer ipv4:74.125.197.95:443","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Missing or insufficient permissions.","grpc_status":7}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_bot.py", line 128, in task_loop
    sys.exit(utasks.uworker_bot_main())
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/__init__.py", line 220, in uworker_bot_main
    uworker_main(input_download_url)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/__init__.py", line 202, in uworker_main
    uworker_output = utask_module.utask_main(uworker_input)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/utasks/variant_task.py", line 105, in utask_main
    testcase, uworker_input.job_type, uworker_input.setup_input)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/setup.py", line 299, in setup_testcase
    prepare_environment_for_testcase(testcase, job_type, task_name)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/setup.py", line 173, in prepare_environment_for_testcase
    app_args = _get_application_arguments(testcase, job_type, task_name)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/tasks/setup.py", line 119, in _get_application_arguments
    job_type, 'APP_ARGS', default='')
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/datastore/data_handler.py", line 1220, in get_value_from_job_definition
    job = data_types.Job.query(data_types.Job.name == job_type).get()
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/query.py", line 1229, in wrapper
    return wrapped(self, *dummy_args, _options=query_options)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/utils.py", line 78, in wrapper
    return wrapped(*args, **new_kwargs)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/utils.py", line 110, in positional_wrapper
    return wrapped(*args, **kwds)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/query.py", line 2063, in get
    return self.get_async(_options=kwargs["_options"]).result()
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 193, in result
    self.check_success()
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 140, in check_success
    raise self._exception
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 312, in _advance_tasklet
    self.generator.throw(type(error), error, traceback)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/query.py", line 2097, in get_async
    results = yield _datastore_query.fetch(options)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 312, in _advance_tasklet
    self.generator.throw(type(error), error, traceback)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/_datastore_query.py", line 108, in fetch
    while (yield results.has_next_async()):
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 312, in _advance_tasklet
    self.generator.throw(type(error), error, traceback)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/_datastore_query.py", line 267, in has_next_async
    yield self._next_batch()  # First time
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 312, in _advance_tasklet
    self.generator.throw(type(error), error, traceback)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/_datastore_query.py", line 297, in _next_batch
    response = yield _datastore_run_query(query)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 312, in _advance_tasklet
    self.generator.throw(type(error), error, traceback)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/_datastore_query.py", line 878, in _datastore_run_query
    "RunQuery", request, timeout=query.timeout
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 312, in _advance_tasklet
    self.generator.throw(type(error), error, traceback)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/_retry.py", line 77, in retry_wrapper
    raise error
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/_retry.py", line 72, in retry_wrapper
    result = yield result
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 312, in _advance_tasklet
    self.generator.throw(type(error), error, traceback)
  File "/mnt/scratch0/clusterfuzz/src/third_party/google/cloud/ndb/_datastore_api.py", line 97, in rpc_call
    raise error
google.api_core.exceptions.PermissionDenied: 403 Missing or insufficient permissions.
```

**Comment by jonathanmetzman** [comment]
This has been fixed.
