### ISSUE TITLE
Ensure manage_vms passes

### ISSUE THREAD

**Issue by jonathanmetzman** [google/clusterfuzz#4183]
Last one failed with 
```
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_cron.py", line 67, in <module>
    sys.exit(main())
  File "/mnt/scratch0/clusterfuzz/src/python/bot/startup/run_cron.py", line 63, in main
    return 0 if task_module.main() else 1
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/cron/manage_vms.py", line 781, in main
    manager.update_clusters()
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/cron/manage_vms.py", line 379, in update_clusters
    high_end_project_infos, cluster)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/cron/manage_vms.py", line 685, in update_project_cpus
    self.assign_hosts_to_workers(self.worker_to_assignment[cluster.name])
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/cron/manage_vms.py", line 728, in assign_hosts_to_workers
    if host_cluster.gce_zone != worker_cluster.gce_zone:
AttributeError: 'NoneType' object has no attribute 'gce_zone'
```

**Comment by vitorguidi** [comment]
This LoC erroring out depends solely on the clusterfuzz-config files being loaded improperly
Managed to run manage_vms locally with a debugger (unfortunately it broke before completing bc of some weird ssh error), and these LoC did not error out

![image](https://github.com/user-attachments/assets/bc29048e-8e20-4f8b-b45a-b4872a31f5e8)

**Comment by vitorguidi** [comment]
I landed this [commit](https://github.com/google/clusterfuzz/pull/4163/commits/1339b5870666a9ca33bd00d5807930606aa06e07) from the 3.7 branch and we are apparently through zone8
![image](https://github.com/user-attachments/assets/b536651d-4f67-4466-be84-c70943fffc88)
:shrug:

**Comment by vitorguidi** [comment]
![image](https://github.com/user-attachments/assets/d03c73c8-75da-4afe-a4fd-f77cc9063242)
Does not seem broken anymore
