### ISSUE TITLE
Local setup clusterfuzz - issue with ndb can't get data

### ISSUE THREAD

**Issue by liuhaitao1106** [google/clusterfuzz#4335]
I am trying to deploy clusterfuzz locally. In fact, it was normal a few days ago, but today I found a lot of this error in the console, and all pages were inaccessible. I would like to ask how I can solve this problem:

ERROR:root:Maximum number of 3 retries exceeded while calling <function make_call.<locals>.rpc_call at 0x7f886050f7e0>, last exception: None
| Traceback (most recent call last):
|   File "/opt/src/clusterfuzz/src/appengine/handlers/base_handler.py", line 281, in dispatch_request
|     return super().dispatch_request(*args, **kwargs)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/appengine/third_party/flask/views.py", line 188, in dispatch_request
|     return current_app.ensure_sync(meth)(**kwargs)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/appengine/libs/handler.py", line 354, in wrapper
|     response = make_response(func(self))
|                              ^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/appengine/libs/handler.py", line 231, in wrapper
|     return func(self)
|            ^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/appengine/handlers/testcase_detail/show.py", line 628, in post
|     return self.render_json(get_testcase_detail_by_id(testcase_id))
|                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/appengine/handlers/testcase_detail/show.py", line 303, in get_testcase_detail_by_id
|     return get_testcase_detail(testcase)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/appengine/handlers/testcase_detail/show.py", line 501, in get_testcase_detail
|     form.generate_csrf_token(),
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/appengine/libs/form.py", line 39, in generate_csrf_token
|     ndb_utils.delete_multi(tokens_to_delete)
|   File "/opt/src/clusterfuzz/src/appengine/clusterfuzz/_internal/datastore/ndb_utils.py", line 77, in delete_multi
|     ndb.delete_multi(chunk)
|   File "/opt/src/clusterfuzz/src/third_party/google/cloud/ndb/_options.py", line 102, in wrapper
|     return wrapped(*pass_args, **kwargs)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/third_party/google/cloud/ndb/utils.py", line 150, in positional_wrapper
|     return wrapped(*args, **kwds)
|            ^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/third_party/google/cloud/ndb/model.py", line 6597, in delete_multi
|     return [future.result() for future in futures]
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/third_party/google/cloud/ndb/model.py", line 6597, in <listcomp>
|     return [future.result() for future in futures]
|             ^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 210, in result
|     self.check_success()
|   File "/opt/src/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 157, in check_success
|     raise self._exception
|   File "/opt/src/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 319, in _advance_tasklet
|     yielded = self.generator.throw(type(error), error, traceback)
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/third_party/google/cloud/ndb/key.py", line 1067, in delete
|     result = yield _datastore_api.delete(self._key, _options)
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 319, in _advance_tasklet
|     yielded = self.generator.throw(type(error), error, traceback)
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/third_party/google/cloud/ndb/_datastore_api.py", line 449, in delete
|     yield batch.delete(key)
|   File "/opt/src/clusterfuzz/src/third_party/google/cloud/ndb/tasklets.py", line 323, in _advance_tasklet
|     yielded = self.generator.send(send_value)
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/opt/src/clusterfuzz/src/third_party/google/cloud/ndb/_retry.py", line 107, in retry_wrapper
|     raise core_exceptions.RetryError(
| google.api_core.exceptions.RetryError: Maximum number of 3 retries exceeded while calling <function make_call.<locals>.rpc_call at 0x7f886050f7e0>, last exception: None

**Comment by liuhaitao1106** [comment]
I found the problem. It seemed that I deleted a certain directory. I rebuilt the index.yaml file and it's back to normal now.
2024-10-17 10:50:42,923 INFO     ___FILE_ONLY___ [datastore] SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@662cccc4

2024-10-17 10:50:42,923 INFO     ___FILE_ONLY___ [datastore] com.google.apphosting.utils.config.AppEngineConfigException: Empty index configuration. The index.yaml file should at least have an empty 'indexes:' block.

2024-10-17 10:50:42,923 INFO     ___FILE_ONLY___ [datastore]    at com.google.apphosting.utils.config.IndexYamlReader.parse(IndexYamlReader.java:169)

2024-10-17 10:50:42,923 INFO     ___FILE_ONLY___ [datastore]    at com.google.apphosting.utils.config.IndexYamlReader.parse(IndexYamlReader.java:189)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at com.google.cloud.datastore.emulator.impl.LocalCompositeIndexManager$YamlIndexFileManager.read(LocalCompositeIndexManager.java:610)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at com.google.cloud.datastore.emulator.impl.LocalCompositeIndexManager.maybeUpdateIndexFile(LocalCompositeIndexManager.java:886)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at com.google.cloud.datastore.emulator.impl.LocalCompositeIndexManager.processQuery(LocalCompositeIndexManager.java:862)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub.lambda$runQuery$6(LocalDatastoreFileStub.java:396)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at java.base/java.security.AccessController.doPrivileged(Native Method)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub.runQuery(LocalDatastoreFileStub.java:392)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1.runQuery(CloudDatastoreV1.java:627)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at com.google.cloud.datastore.emulator.v1.DatastoreV1Emulator.runQuery(DatastoreV1Emulator.java:64)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at com.google.cloud.datastore.emulator.v1.DatastoreEmulatorGrpcAdapter$1.runQuery(DatastoreEmulatorGrpcAdapter.java:87)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at com.google.datastore.v1.DatastoreGrpc$MethodHandlers.invoke(DatastoreGrpc.java:695)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:346)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

2024-10-17 10:50:42,924 INFO     ___FILE_ONLY___ [datastore]    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)

2024-10-17 10:50:42,925 INFO     ___FILE_ONLY___ [datastore]    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

2024-10-17 10:50:42,925 INFO     ___FILE_ONLY___ [datastore]    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

2024-10-17 10:50:42,925 INFO     ___FILE_ONLY___ [datastore]    at java.base/java.lang.Thread.run(Thread.java:829)
