### ISSUE TITLE
nodeenv issue during 2.6.0 installation

### ISSUE THREAD

**Issue by 0x0abd** [google/clusterfuzz#4408]
Hi folks. Use CF often and never seen such issue before. Any suggestions?
It happens on installing dependencies:

```bash
+ nodeenv -p --prebuilt
Traceback (most recent call last):
  File "/home/vagrant/.local/share/virtualenvs/clusterfuzz-mEvB2Z9p/bin/nodeenv", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/.local/share/virtualenvs/clusterfuzz-mEvB2Z9p/lib/python3.7/site-packages/nodeenv.py", line 918, in main
    opt.node = get_last_stable_node_version()
  File "/home/vagrant/.local/share/virtualenvs/clusterfuzz-mEvB2Z9p/lib/python3.7/site-packages/nodeenv.py", line 872, in get_last_stable_node_version
    return links[-1][0]
IndexError: list index out of range
```

**Comment by reach-satori** [comment]
Having the same issue on pre-commit,  Probably means it's not a cf issue.

**Comment by stuertz** [comment]
I worked around this using a local pre-commit installation:

```sh
$ apt remove pre-commit
$ apt install pipx
$ pipx install pre-commit
$ ~/.local/bin/pre-commit   # or add to your path
```
