### ISSUE TITLE
Fix proto exception in triage cron.

### ISSUE THREAD

**Issue by inferno-chromium** [google/clusterfuzz#690]
```
| ERROR    2019-07-16 18:42:03,137 wsgi.py:263]
| Traceback (most recent call last):
|   File "/build/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
|     handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
|   File "/build/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
|     handler, path, err = LoadObject(self._handler)
|   File "/build/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
|     obj = __import__(path[0])
|   File "/build/clusterfuzz/src/appengine/server.py", line 22, in <module>
|     from handlers import base_handler
|   File "/build/clusterfuzz/src/appengine/handlers/base_handler.py", line 39, in <module>
|     from libs import form
|   File "/build/clusterfuzz/src/appengine/libs/form.py", line 23, in <module>
|     from libs import helpers
|   File "/build/clusterfuzz/src/appengine/libs/helpers.py", line 22, in <module>
|     from datastore import data_handler
|   File "/build/clusterfuzz/src/appengine/python/datastore/data_handler.py", line 27, in <module>
|     from base import tasks
|   File "/build/clusterfuzz/src/appengine/python/base/tasks.py", line 27, in <module>
|     from datastore import ndb_utils
|   File "/build/clusterfuzz/src/appengine/python/datastore/ndb_utils.py", line 17, in <module>
|     from datastore import ndb_patcher
|   File "/build/clusterfuzz/src/appengine/python/datastore/ndb_patcher.py", line 37, in <module>
|     from google.cloud import datastore
|   File "/build/clusterfuzz/src/appengine/third_party/google/cloud/datastore/__init__.py", line 61, in <module>
|     from google.cloud.datastore.batch import Batch
|   File "/build/clusterfuzz/src/appengine/third_party/google/cloud/datastore/batch.py", line 24, in <module>
|     from google.cloud.datastore import helpers
|   File "/build/clusterfuzz/src/appengine/third_party/google/cloud/datastore/helpers.py", line 29, in <module>
|     from google.cloud.datastore_v1.proto import datastore_pb2
| INFO     2019-07-16 18:42:03,144 module.py:861] default: "GET /jobs HTTP/1.1" 500 -
|   File "/build/clusterfuzz/src/appengine/third_party/google/cloud/datastore_v1/__init__.py", line 17, in <module>
|     from google.cloud.datastore_v1 import types
|   File "/build/clusterfuzz/src/appengine/third_party/google/cloud/datastore_v1/types.py", line 26, in <module>
|     from google.cloud.datastore_v1.proto import datastore_pb2
|   File "/build/clusterfuzz/src/appengine/third_party/google/cloud/datastore_v1/proto/datastore_pb2.py", line 17, in <module>
|     from google.cloud.datastore_v1.proto import entity_pb2 as google_dot_cloud_dot_datastore__v1_dot_proto_dot_entity__pb2
|   File "/build/clusterfuzz/src/appengine/third_party/google/cloud/datastore_v1/proto/entity_pb2.py", line 471, in <module>
|     _sym_db.RegisterMessage(PartitionId)
|   File "/build/clusterfuzz/ENV/lib/python2.7/site-packages/google/protobuf/symbol_database.py", line 82, in RegisterMessage
|     self.RegisterMessageDescriptor(desc)
|   File "/build/clusterfuzz/ENV/lib/python2.7/site-packages/google/protobuf/symbol_database.py", line 91, in RegisterMessageDescriptor
|     self.pool.AddDescriptor(message_descriptor)
|   File "/build/clusterfuzz/ENV/lib/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 215, in AddDescriptor
|     self._CheckConflictRegister(desc, desc.full_name, desc.file.name)
|   File "/build/clusterfuzz/ENV/lib/python2.7/site-packages/google/protobuf/descriptor_pool.py", line 175, in _CheckConflictRegister
|     raise TypeError(error_msg)
| TypeError: Conflict register for file "google/cloud/datastore_v1/proto/entity.proto": google.datastore.v1.PartitionId is already defined in file "google/cloud/proto/datastore/v1/entity.proto". Please fix the conflict by adding package name on the proto file, or use different name for the duplication.
```

**Comment by inferno-chromium** [comment]
@oliverchang - assigning for your sheriff rotation. somehow that hack we had for preventing proto conflict is not working. need to wait like 60-sec for cron to run or can just do localhost:9002/cron

**Comment by inferno-chromium** [comment]
Verified.
