### ISSUE TITLE
/fuzz-strategy-selection cron is failing on external

### ISSUE THREAD

**Issue by Dor1s** [google/clusterfuzz#721]
I didn't try to re-run it manually, assuming that it's on radar of @mbarbella-chromium and @mukundv-chrome

**Comment by inferno-chromium** [comment]
```
Retrying on google_cloud_utils.big_query.Client.insert failed with <HttpError 400 when requesting https://www.googleapis.com/bigquery/v2/projects/clusterfuzz-external/datasets/main/tables/fuzz_strategy_experiments/insertAll?alt=json returned "No rows present in the request.">. Raise. (/base/data/home/apps/s~clusterfuzz-external/cron-service:20190722t231009.419789316583923473/python/metrics/logs.py:329)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/runtime/runtime.py", line 166, in HandleRequest
    error)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 341, in HandleRequest
    return WsgiRequest(environ, handler_name, url, post_data, error).Handle()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 273, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/941d77da994078b1/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~clusterfuzz-external/cron-service:20190722t231009.419789316583923473/libs/handler.py", line 95, in wrapper
    return func(self)
  File "/base/data/home/apps/s~clusterfuzz-external/cron-service:20190722t231009.419789316583923473/handlers/cron/fuzz_strategy_selection.py", line 223, in get
    _query_and_upload_strategy_probabilities()
  File "/base/data/home/apps/s~clusterfuzz-external/cron-service:20190722t231009.419789316583923473/handlers/cron/fuzz_strategy_selection.py", line 211, in _query_and_upload_strategy_probabilities
    _store_probabilities_in_bigquery(data)
  File "/base/data/home/apps/s~clusterfuzz-external/cron-service:20190722t231009.419789316583923473/handlers/cron/fuzz_strategy_selection.py", line 181, in _store_probabilities_in_bigquery
    client.insert(bigquery_data)
  File "/base/data/home/apps/s~clusterfuzz-external/cron-service:20190722t231009.419789316583923473/python/system/environment.py", line 947, in wrapper
    return func(*args, **kwargs)
  File "/base/data/home/apps/s~clusterfuzz-external/cron-service:20190722t231009.419789316583923473/python/base/retry.py", line 102, in _wrapper
    if not handle_retry(num_try, exception=e):
  File "/base/data/home/apps/s~clusterfuzz-external/cron-service:20190722t231009.419789316583923473/python/base/retry.py", line 79, in handle_retry
    total=tries)
LogError: Retrying on google_cloud_utils.big_query.Client.insert failed with <HttpError 400 when requesting https://www.googleapis.com/bigquery/v2/projects/clusterfuzz-external/datasets/main/tables/fuzz_strategy_experiments/insertAll?alt=json returned "No rows present in the request.">. Raise.
Traceback (most recent call last):
  File "/base/data/home/apps/s~clusterfuzz-external/cron-service:20190722t231009.419789316583923473/python/base/retry.py", line 89, in _wrapper
    result = func(*args, **kwargs)
  File "/base/data/home/apps/s~clusterfuzz-external/cron-service:20190722t231009.419789316583923473/python/google_cloud_utils/big_query.py", line 354, in insert
    body=body).execute()
  File "/base/data/home/apps/s~clusterfuzz-external/cron-service:20190722t231009.419789316583923473/third_party/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/base/data/home/apps/s~clusterfuzz-external/cron-service:20190722t231009.419789316583923473/third_party/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 400 when requesting https://www.googleapis.com/bigquery/v2/projects/clusterfuzz-external/datasets/main/tables/fuzz_strategy_experiments/insertAll?alt=json returned "No rows present in the request.">
```
